/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account-movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a deposit, withdrawal or transfer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.AccountMovementInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.AccountMovement"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account-movements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a movement */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description movement id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.AccountMovementInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.AccountMovement"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a movement */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description movement id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["httpapi.loginInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Session"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the refresh cookie for a new access token (rotates the cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Session"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and start a session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description account */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["service.RegisterInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Session"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments made to credit cards */
        get: {
            parameters: {
                query?: {
                    /** @description card */
                    payment_method_id?: number;
                    /** @description YYYY-MM-DD */
                    from?: string;
                    /** @description YYYY-MM-DD */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.CardPayment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Record a payment to a credit card (a transfer, not spending) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description payment */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["service.CardPaymentInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.CardPayment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a card payment */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description card payment id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: {
            parameters: {
                query?: {
                    /** @description expense or income */
                    kind?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.Category"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.CategoryInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Category"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a category (kind cannot change) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description category id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.CategoryInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Category"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a category; if it is in use, pass reassign_to */
        delete: {
            parameters: {
                query?: {
                    /** @description category that inherits all references */
                    reassign_to?: number;
                };
                header?: never;
                path: {
                    /** @description category id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category-budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monthly category limits */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.CategoryBudget"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category-budgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set (create or replace) a category's monthly limit */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description expense category id */
                    id: number;
                };
                cookie?: never;
            };
            /** @description limit in cents */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["httpapi.budgetInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.CategoryBudget"];
                    };
                };
            };
        };
        post?: never;
        /** Remove a category's monthly limit */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description category id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending grouped by category or payment method */
        get: {
            parameters: {
                query: {
                    /** @description category or payment_method */
                    by: string;
                    /** @description YYYY-MM-DD */
                    from: string;
                    /** @description YYYY-MM-DD */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.BreakdownItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debt summary per active credit card (inactive cards too while they carry a balance) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.CardSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending per day, ISO week or month (empty buckets are 0) */
        get: {
            parameters: {
                query: {
                    /** @description day, week or month */
                    period: string;
                    /** @description YYYY-MM-DD */
                    from: string;
                    /** @description YYYY-MM-DD */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.SeriesPoint"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Month summary: income, fixed, installments, spent, available, safe-to-spend, budgets */
        get: {
            parameters: {
                query?: {
                    /** @description YYYY-MM (default: current month in the user's timezone) */
                    month?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Summary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming fixed payments and card payment due dates */
        get: {
            parameters: {
                query?: {
                    /** @description 7-60, default 7 */
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.UpcomingItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update one month's row (amount, status, settled_on, payment method)
         * @description settled_on defaults to today; when given it must be between the month's first day minus 31 days and today plus 1 day.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description entry id */
                    id: number;
                };
                cookie?: never;
            };
            /** @description changes */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["service.EntryUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Entry"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List expenses, newest first, cursor-paginated */
        get: {
            parameters: {
                query?: {
                    /** @description YYYY-MM-DD */
                    from?: string;
                    /** @description YYYY-MM-DD */
                    to?: string;
                    /** @description category */
                    category_id?: number;
                    /** @description payment method */
                    payment_method_id?: number;
                    /** @description search in description */
                    q?: string;
                    /** @description next_cursor from the previous page */
                    cursor?: string;
                    /** @description 1-200, default 50 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.ExpensePage"];
                    };
                };
            };
        };
        put?: never;
        /** Record an expense */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.ExpenseInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Expense"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace an expense */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description expense id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.ExpenseInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Expense"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an expense */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description expense id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/entries.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download income, fixed and installment rows as CSV */
        get: {
            parameters: {
                query: {
                    /** @description YYYY-MM-DD */
                    from: string;
                    /** @description YYYY-MM-DD */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/expenses.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download expenses as CSV */
        get: {
            parameters: {
                query: {
                    /** @description YYYY-MM-DD */
                    from: string;
                    /** @description YYYY-MM-DD */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/savings.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download savings openings, movements and value updates as CSV */
        get: {
            parameters: {
                query: {
                    /** @description YYYY-MM-DD */
                    from: string;
                    /** @description YYYY-MM-DD */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fixed-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recurring fixed payments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.FixedPayment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a recurring fixed payment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.FixedPaymentInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.FixedPayment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fixed-payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a fixed payment; pending, unedited rows from the current month on follow the change */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description fixed payment id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.FixedPaymentInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.FixedPayment"];
                    };
                };
            };
        };
        post?: never;
        /** Deactivate a fixed payment; end_month becomes the current month (null if it has not started), so past months keep it */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description fixed payment id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.FixedPayment"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/income-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recurring income sources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.IncomeSource"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a recurring income source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.IncomeSourceInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.IncomeSource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/income-sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace an income source; pending, unedited rows from the current month on follow the change */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description income source id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.IncomeSourceInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.IncomeSource"];
                    };
                };
            };
        };
        post?: never;
        /** Deactivate an income source; end_month becomes the current month (null if it has not started), so past months keep it */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description income source id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.IncomeSource"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/installment-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List MSI (meses sin intereses) plans */
        get: {
            parameters: {
                query?: {
                    /** @description card */
                    payment_method_id?: number;
                    /** @description exclude cancelled plans */
                    active_only?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.InstallmentPlan"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an MSI plan on a credit card */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.InstallmentPlanInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.InstallmentPlan"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/installment-plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace an MSI plan (only description/category once billing started) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description plan id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.InstallmentPlanInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.InstallmentPlan"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Cancel an MSI plan (refund/cancellation); unbilled installments leave the debt */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description plan id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.InstallmentPlan"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.User"];
                    };
                };
            };
        };
        /** Update profile (name, currency, locale, timezone) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description profile */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["service.ProfileInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.User"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Permanently delete the account and all its data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description current password */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["httpapi.deleteAccountInput"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/months/{month}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income, fixed and installment rows for a month (generated on first read) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description YYYY-MM */
                    month: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.Entry"][];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payment methods (cards are reference data: last 4 digits only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.PaymentMethod"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a payment method */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.PaymentMethodInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.PaymentMethod"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-methods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a payment method */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description payment method id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.PaymentMethod"];
                    };
                };
            };
        };
        /** Replace a payment method's editable fields (type cannot change) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description payment method id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.PaymentMethodInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.PaymentMethod"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an unused payment method (deactivate used ones instead) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description payment method id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-methods/{id}/statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credit-card statement for a cycle (default: the one currently due) */
        get: {
            parameters: {
                query?: {
                    /** @description YYYY-MM */
                    cycle?: string;
                };
                header?: never;
                path: {
                    /** @description card id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.Statement"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List savings and investment accounts with computed balances */
        get: {
            parameters: {
                query?: {
                    /** @description include archived accounts */
                    include_archived?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.SavingsAccount"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a savings or investment account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.SavingsAccountInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.SavingsAccount"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One account with its goals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description account id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.SavingsAccountDetail"];
                    };
                };
            };
        };
        /** Replace an account (archived=true archives it; the opening is locked once it has history) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description account id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.SavingsAccountInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.SavingsAccount"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an account with no history (409 account_has_history otherwise) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description account id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-accounts/{id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An account's movements (both sides of transfers), newest first */
        get: {
            parameters: {
                query?: {
                    /** @description YYYY-MM-DD */
                    from?: string;
                    /** @description YYYY-MM-DD */
                    to?: string;
                };
                header?: never;
                path: {
                    /** @description account id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.AccountMovement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-accounts/{id}/valuations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An account's value updates, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description account id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.AccountValuation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-accounts/{id}/valuations/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record the account's value on a date (one per day; replaces) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description account id */
                    id: number;
                    /** @description YYYY-MM-DD */
                    date: string;
                };
                cookie?: never;
            };
            /** @description value */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["service.ValuationInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.AccountValuation"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a value update */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description account id */
                    id: number;
                    /** @description YYYY-MM-DD */
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List savings goals with progress and status */
        get: {
            parameters: {
                query?: {
                    /** @description include archived goals */
                    include_archived?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.SavingsGoal"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a savings goal on an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.SavingsGoalInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.SavingsGoal"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpapi.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-goals/emergency-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggested emergency-fund target from recent months */
        get: {
            parameters: {
                query: {
                    /** @description 3 or 6 */
                    months: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.EmergencySuggestion"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings-goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a goal (its account cannot change) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description goal id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["service.SavingsGoalInput"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.SavingsGoal"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a goal (its movements stay, untagged) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description goal id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth, this month's savings, allocation and insurance warnings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["service.SavingsOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Month-end value and money put in, per month (at most 24 months) */
        get: {
            parameters: {
                query: {
                    /** @description YYYY-MM */
                    from: string;
                    /** @description YYYY-MM */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["service.SavingsPoint"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "apperr.Error": {
            code?: string;
            fields?: {
                [key: string]: string;
            };
            message?: string;
        };
        "httpapi.ErrorResponse": {
            error?: components["schemas"]["apperr.Error"];
        };
        "httpapi.budgetInput": {
            monthly_limit: number;
        };
        "httpapi.deleteAccountInput": {
            password: string;
        };
        "httpapi.loginInput": {
            email: string;
            password: string;
        };
        "service.AccountMovement": {
            account_id: number;
            amount: number;
            created_at: string;
            goal_id?: number;
            id: number;
            /** @enum {string} */
            kind: "deposit" | "withdrawal" | "transfer";
            note: string;
            occurred_on: string;
            to_account_id?: number;
        };
        "service.AccountMovementInput": {
            account_id: number;
            amount: number;
            goal_id?: number;
            /** @enum {string} */
            kind: "deposit" | "withdrawal" | "transfer";
            note?: string;
            occurred_on: string;
            to_account_id?: number;
        };
        "service.AccountValuation": {
            value: number;
            valued_on: string;
        };
        "service.AllocationSlice": {
            amount: number;
            kind: string;
            pct: number;
        };
        "service.BreakdownItem": {
            amount: number;
            color: string;
            id?: number;
            name: string;
        };
        "service.BudgetStatus": {
            category_id: number;
            color: string;
            limit: number;
            name: string;
            pct: number;
            spent: number;
        };
        "service.CardPayment": {
            amount: number;
            id: number;
            note: string;
            paid_on: string;
            payment_method_id: number;
        };
        "service.CardPaymentInput": {
            amount: number;
            note: string;
            paid_on: string;
            payment_method_id: number;
        };
        "service.CardSummary": {
            amount_due: number;
            available_credit?: number;
            color: string;
            credit_limit?: number;
            current_balance: number;
            cycle: string;
            due_on: string;
            last4?: string;
            nickname: string;
            payment_method_id: number;
            utilization?: number;
        };
        "service.Category": {
            color: string;
            icon: string;
            id: number;
            kind: string;
            name: string;
        };
        "service.CategoryBudget": {
            category_id: number;
            monthly_limit: number;
        };
        "service.CategoryInput": {
            color: string;
            icon: string;
            kind: string;
            name: string;
        };
        "service.EmergencySuggestion": {
            monthly_need: number;
            months: number;
            target: number;
        };
        "service.Entry": {
            amount: number;
            category_id?: number;
            due_date: string;
            edited: boolean;
            fixed_payment_id?: number;
            id: number;
            income_source_id?: number;
            installment_no?: number;
            installment_plan_id?: number;
            kind: string;
            month: string;
            name: string;
            payment_method_id?: number;
            settled_on?: string;
            status: string;
        };
        "service.EntryUpdate": {
            amount: number;
            payment_method_id?: number;
            settled_on?: string;
            status: string;
        };
        "service.Expense": {
            amount: number;
            category_id: number;
            created_at: string;
            description: string;
            id: number;
            payment_method_id?: number;
            spent_on: string;
        };
        "service.ExpenseInput": {
            amount: number;
            category_id: number;
            description: string;
            payment_method_id?: number;
            spent_on: string;
        };
        "service.ExpensePage": {
            items: components["schemas"]["service.Expense"][];
            next_cursor?: string;
        };
        "service.FixedPayment": {
            active: boolean;
            amount: number;
            category_id: number;
            day_of_month: number;
            end_month?: string;
            id: number;
            name: string;
            payment_method_id?: number;
            start_month: string;
        };
        "service.FixedPaymentInput": {
            active?: boolean;
            amount: number;
            category_id: number;
            day_of_month: number;
            end_month?: string;
            name: string;
            payment_method_id?: number;
            start_month: string;
        };
        "service.IncomeSource": {
            active: boolean;
            amount: number;
            anchor_date?: string;
            category_id?: number;
            day_of_month: number;
            end_month?: string;
            /** @enum {string} */
            frequency: "monthly" | "semimonthly" | "biweekly" | "weekly";
            id: number;
            name: string;
            second_day?: number;
            start_month: string;
        };
        "service.IncomeSourceInput": {
            active?: boolean;
            amount: number;
            anchor_date?: string;
            category_id?: number;
            day_of_month?: number;
            end_month?: string;
            /** @enum {string} */
            frequency?: "monthly" | "semimonthly" | "biweekly" | "weekly";
            name: string;
            second_day?: number;
            start_month: string;
        };
        "service.InstallmentPlan": {
            billed_count: number;
            cancelled_on?: string;
            category_id: number;
            description: string;
            first_cycle: string;
            id: number;
            installment_amount: number;
            installments: number;
            payment_method_id: number;
            purchased_on: string;
            remaining_amount: number;
            total_amount: number;
        };
        "service.InstallmentPlanInput": {
            category_id: number;
            description: string;
            installments: number;
            payment_method_id: number;
            purchased_on: string;
            total_amount: number;
        };
        "service.InsuranceWarning": {
            excess: number;
            institution: string;
            kind: string;
            limit: number;
            total: number;
        };
        "service.PaymentMethod": {
            active: boolean;
            bank?: string;
            color: string;
            credit_limit?: number;
            id: number;
            last4?: string;
            network?: string;
            nickname: string;
            opening_balance: number;
            opening_balance_date?: string;
            payment_due_day?: number;
            statement_day?: number;
            type: string;
        };
        "service.PaymentMethodInput": {
            active?: boolean;
            bank?: string;
            color: string;
            credit_limit?: number;
            last4?: string;
            network?: string;
            nickname: string;
            opening_balance: number;
            opening_balance_date?: string;
            payment_due_day?: number;
            statement_day?: number;
            type: string;
        };
        "service.ProfileInput": {
            currency: string;
            locale: string;
            name: string;
            timezone: string;
        };
        "service.RegisterInput": {
            currency: string;
            email: string;
            locale: string;
            name: string;
            password: string;
            timezone: string;
        };
        "service.SavingsAccount": {
            anchor_date: string;
            annual_rate_bp?: number;
            archived_on?: string;
            balance: number;
            color: string;
            estimated_yield?: number;
            gain: number;
            gain_pct?: number;
            has_history: boolean;
            has_money_history: boolean;
            id: number;
            institution: string;
            insured: boolean;
            kind: string;
            name: string;
            opening_balance: number;
            opening_date: string;
            put_in: number;
            stale: boolean;
        };
        "service.SavingsAccountDetail": {
            account: components["schemas"]["service.SavingsAccount"];
            goals: components["schemas"]["service.SavingsGoal"][];
        };
        "service.SavingsAccountInput": {
            annual_rate_bp?: number;
            archived?: boolean;
            color?: string;
            institution: string;
            kind: string;
            name: string;
            opening_balance?: number;
            opening_date: string;
        };
        "service.SavingsGoal": {
            account_id: number;
            achieved_on?: string;
            archived: boolean;
            behind_by?: number;
            color: string;
            emergency_months?: number;
            icon: string;
            id: number;
            kind: string;
            monthly_amount?: number;
            name: string;
            pct: number;
            planned_this_month: number;
            progress: number;
            remaining: number;
            required_monthly?: number;
            start_month: string;
            starting_amount: number;
            /** @enum {string} */
            status: "achieved" | "no_date" | "ahead" | "on_track" | "behind";
            target_amount: number;
            target_date?: string;
        };
        "service.SavingsGoalInput": {
            account_id: number;
            archived?: boolean;
            color?: string;
            emergency_months?: number;
            icon?: string;
            kind?: string;
            monthly_amount?: number;
            name: string;
            starting_amount?: number;
            target_amount: number;
            target_date?: string;
        };
        "service.SavingsMonth": {
            deposited: number;
            planned: number;
            saved: number;
            withdrawn: number;
        };
        "service.SavingsOverview": {
            allocation: components["schemas"]["service.AllocationSlice"][];
            assets: number;
            card_debt: number;
            insurance_warnings: components["schemas"]["service.InsuranceWarning"][];
            month: components["schemas"]["service.SavingsMonth"];
            net_worth: number;
            udi_value: number;
        };
        "service.SavingsPoint": {
            month: string;
            put_in: number;
            value: number;
        };
        "service.SeriesPoint": {
            committed: number;
            expenses: number;
            start: string;
        };
        "service.Session": {
            access_token: string;
            user: components["schemas"]["service.User"];
        };
        "service.Statement": {
            amount_due: number;
            available_credit?: number;
            billed_balance: number;
            charges: components["schemas"]["service.StatementCharge"][];
            closes_on: string;
            credit_limit?: number;
            current_balance: number;
            cycle: string;
            due_on: string;
            installments: components["schemas"]["service.StatementInstallment"][];
            opens_on: string;
            payment_method_id: number;
            payments: components["schemas"]["service.CardPayment"][];
            /**
             * @description PaymentsAfterClose are payments in (closes_on, due_on]; they reduce
             *     amount_due below billed_balance.
             */
            payments_after_close: components["schemas"]["service.CardPayment"][];
            utilization?: number;
        };
        "service.StatementCharge": {
            amount: number;
            date: string;
            description: string;
            source: string;
        };
        "service.StatementInstallment": {
            amount: number;
            description: string;
            no: number;
            of: number;
            plan_id: number;
        };
        "service.Summary": {
            available: number;
            budgets: components["schemas"]["service.BudgetStatus"][];
            currency: string;
            days_remaining?: number;
            fixed_committed: number;
            fixed_paid: number;
            income: number;
            installments: number;
            month: string;
            safe_to_spend_per_day?: number;
            saved: number;
            saved_deposited: number;
            saved_planned: number;
            saved_withdrawn: number;
            spent: number;
        };
        "service.UpcomingItem": {
            amount: number;
            date: string;
            entry_id?: number;
            name: string;
            overdue: boolean;
            payment_method_id?: number;
            type: string;
        };
        "service.User": {
            created_at: string;
            currency: string;
            email: string;
            id: number;
            locale: string;
            name: string;
            timezone: string;
        };
        "service.ValuationInput": {
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description category */
        "service.CategoryInput": {
            content: {
                "application/json": components["schemas"]["service.CategoryInput"];
            };
        };
        /** @description account */
        "service.SavingsAccountInput": {
            content: {
                "application/json": components["schemas"]["service.SavingsAccountInput"];
            };
        };
        /** @description plan */
        "service.InstallmentPlanInput": {
            content: {
                "application/json": components["schemas"]["service.InstallmentPlanInput"];
            };
        };
        /** @description goal */
        "service.SavingsGoalInput": {
            content: {
                "application/json": components["schemas"]["service.SavingsGoalInput"];
            };
        };
        /** @description income source */
        "service.IncomeSourceInput": {
            content: {
                "application/json": components["schemas"]["service.IncomeSourceInput"];
            };
        };
        /** @description payment method */
        "service.PaymentMethodInput": {
            content: {
                "application/json": components["schemas"]["service.PaymentMethodInput"];
            };
        };
        /** @description movement */
        "service.AccountMovementInput": {
            content: {
                "application/json": components["schemas"]["service.AccountMovementInput"];
            };
        };
        /** @description expense */
        "service.ExpenseInput": {
            content: {
                "application/json": components["schemas"]["service.ExpenseInput"];
            };
        };
        /** @description fixed payment */
        "service.FixedPaymentInput": {
            content: {
                "application/json": components["schemas"]["service.FixedPaymentInput"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
