// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with email and password",
                "parameters": [
                    {
                        "description": "credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.loginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Session"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Revoke the refresh cookie",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Exchange the refresh cookie for a new access token (rotates the cookie)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Session"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create an account and start a session",
                "parameters": [
                    {
                        "description": "account",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.Session"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/card-payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "List payments made to credit cards",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "card",
                        "name": "payment_method_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.CardPayment"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Record a payment to a credit card (a transfer, not spending)",
                "parameters": [
                    {
                        "description": "payment",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CardPaymentInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.CardPayment"
                        }
                    }
                }
            }
        },
        "/card-payments/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Delete a card payment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "card payment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "List categories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "expense or income",
                        "name": "kind",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.Category"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Create a category",
                "parameters": [
                    {
                        "description": "category",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CategoryInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.Category"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Update a category (kind cannot change)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "category id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "category",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CategoryInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Category"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Delete a category; if it is in use, pass reassign_to",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "category id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "category that inherits all references",
                        "name": "reassign_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/category-budgets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budgets"
                ],
                "summary": "List monthly category limits",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.CategoryBudget"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/category-budgets/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budgets"
                ],
                "summary": "Set (create or replace) a category's monthly limit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "expense category id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "limit in cents",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.budgetInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CategoryBudget"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "budgets"
                ],
                "summary": "Remove a category's monthly limit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "category id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/dashboard/breakdown": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Spending grouped by category or payment method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category or payment_method",
                        "name": "by",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.BreakdownItem"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/cards": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Debt summary per active credit card",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.CardSummary"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/series": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Spending per day, ISO week or month (empty buckets are 0)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "day, week or month",
                        "name": "period",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.SeriesPoint"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Month summary: income, fixed, installments, spent, available, safe-to-spend, budgets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "YYYY-MM (default: current month in the user's timezone)",
                        "name": "month",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Summary"
                        }
                    }
                }
            }
        },
        "/dashboard/upcoming": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Upcoming fixed payments and card payment due dates",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "7-60, default 7",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.UpcomingItem"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entries/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "months"
                ],
                "summary": "Update one month's row (amount, status, settled_on, payment method)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "entry id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "changes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.EntryUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Entry"
                        }
                    }
                }
            }
        },
        "/expenses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "List expenses, newest first, cursor-paginated",
                "parameters": [
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "category",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "payment method",
                        "name": "payment_method_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search in description",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "next_cursor from the previous page",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "1-200, default 50",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ExpensePage"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "Record an expense",
                "parameters": [
                    {
                        "description": "expense",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ExpenseInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.Expense"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/expenses/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "Replace an expense",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "expense id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "expense",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ExpenseInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Expense"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "Delete an expense",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "expense id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/export/entries.csv": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Download income, fixed and installment rows as CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/export/expenses.csv": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Download expenses as CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/fixed-payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "List recurring fixed payments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.FixedPayment"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "Create a recurring fixed payment",
                "parameters": [
                    {
                        "description": "fixed payment",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.FixedPaymentInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.FixedPayment"
                        }
                    }
                }
            }
        },
        "/fixed-payments/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "Replace a fixed payment; pending, unedited rows from the current month on follow the change",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "fixed payment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "fixed payment",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.FixedPaymentInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.FixedPayment"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "Deactivate a fixed payment; end_month becomes the current month (null if it has not started), so past months keep it",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "fixed payment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.FixedPayment"
                        }
                    }
                }
            }
        },
        "/income-sources": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "List recurring income sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.IncomeSource"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "Create a recurring income source",
                "parameters": [
                    {
                        "description": "income source",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.IncomeSourceInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.IncomeSource"
                        }
                    }
                }
            }
        },
        "/income-sources/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "Replace an income source; pending, unedited rows from the current month on follow the change",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "income source id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "income source",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.IncomeSourceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IncomeSource"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recurring"
                ],
                "summary": "Deactivate an income source; end_month becomes the current month (null if it has not started), so past months keep it",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "income source id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IncomeSource"
                        }
                    }
                }
            }
        },
        "/installment-plans": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "List MSI (meses sin intereses) plans",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "card",
                        "name": "payment_method_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "exclude cancelled plans",
                        "name": "active_only",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.InstallmentPlan"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Create an MSI plan on a credit card",
                "parameters": [
                    {
                        "description": "plan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.InstallmentPlanInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.InstallmentPlan"
                        }
                    }
                }
            }
        },
        "/installment-plans/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Replace an MSI plan (only description/category once billing started)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "plan id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "plan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.InstallmentPlanInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.InstallmentPlan"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Cancel an MSI plan (refund/cancellation); unbilled installments leave the debt",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "plan id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.InstallmentPlan"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Update profile (name, currency, locale, timezone)",
                "parameters": [
                    {
                        "description": "profile",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ProfileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.User"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Permanently delete the account and all its data",
                "parameters": [
                    {
                        "description": "current password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.deleteAccountInput"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/months/{month}/entries": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "months"
                ],
                "summary": "Income, fixed and installment rows for a month (generated on first read)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "YYYY-MM",
                        "name": "month",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.Entry"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payment-methods": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment-methods"
                ],
                "summary": "List payment methods (cards are reference data: last 4 digits only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.PaymentMethod"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment-methods"
                ],
                "summary": "Create a payment method",
                "parameters": [
                    {
                        "description": "payment method",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.PaymentMethodInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.PaymentMethod"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payment-methods/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment-methods"
                ],
                "summary": "Get a payment method",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "payment method id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.PaymentMethod"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment-methods"
                ],
                "summary": "Replace a payment method's editable fields (type cannot change)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "payment method id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "payment method",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.PaymentMethodInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.PaymentMethod"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "payment-methods"
                ],
                "summary": "Delete an unused payment method (deactivate used ones instead)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "payment method id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payment-methods/{id}/statement": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Credit-card statement for a cycle (default: the one currently due)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "card id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM",
                        "name": "cycle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Statement"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apperr.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httpapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/apperr.Error"
                }
            }
        },
        "httpapi.budgetInput": {
            "type": "object",
            "properties": {
                "monthly_limit": {
                    "type": "integer"
                }
            }
        },
        "httpapi.deleteAccountInput": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "httpapi.loginInput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "service.BreakdownItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.BudgetStatus": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "color": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pct": {
                    "type": "integer"
                },
                "spent": {
                    "type": "integer"
                }
            }
        },
        "service.CardPayment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "paid_on": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                }
            }
        },
        "service.CardPaymentInput": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "paid_on": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                }
            }
        },
        "service.CardSummary": {
            "type": "object",
            "properties": {
                "amount_due": {
                    "type": "integer"
                },
                "available_credit": {
                    "type": "integer"
                },
                "color": {
                    "type": "string"
                },
                "credit_limit": {
                    "type": "integer"
                },
                "current_balance": {
                    "type": "integer"
                },
                "cycle": {
                    "type": "string"
                },
                "due_on": {
                    "type": "string"
                },
                "last4": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "utilization": {
                    "type": "number"
                }
            }
        },
        "service.Category": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.CategoryBudget": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "monthly_limit": {
                    "type": "integer"
                }
            }
        },
        "service.CategoryInput": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.Entry": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "due_date": {
                    "type": "string"
                },
                "edited": {
                    "type": "boolean"
                },
                "fixed_payment_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "income_source_id": {
                    "type": "integer"
                },
                "installment_no": {
                    "type": "integer"
                },
                "installment_plan_id": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "month": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "settled_on": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "service.EntryUpdate": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "settled_on": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "service.Expense": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "spent_on": {
                    "type": "string"
                }
            }
        },
        "service.ExpenseInput": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "spent_on": {
                    "type": "string"
                }
            }
        },
        "service.ExpensePage": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.Expense"
                    }
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "service.FixedPayment": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "amount": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "day_of_month": {
                    "type": "integer"
                },
                "end_month": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "start_month": {
                    "type": "string"
                }
            }
        },
        "service.FixedPaymentInput": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "amount": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "day_of_month": {
                    "type": "integer"
                },
                "end_month": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "start_month": {
                    "type": "string"
                }
            }
        },
        "service.IncomeSource": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "amount": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "day_of_month": {
                    "type": "integer"
                },
                "end_month": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "start_month": {
                    "type": "string"
                }
            }
        },
        "service.IncomeSourceInput": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "amount": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "day_of_month": {
                    "type": "integer"
                },
                "end_month": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_month": {
                    "type": "string"
                }
            }
        },
        "service.InstallmentPlan": {
            "type": "object",
            "properties": {
                "billed_count": {
                    "type": "integer"
                },
                "cancelled_on": {
                    "type": "string"
                },
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "first_cycle": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "installment_amount": {
                    "type": "integer"
                },
                "installments": {
                    "type": "integer"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "purchased_on": {
                    "type": "string"
                },
                "remaining_amount": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "integer"
                }
            }
        },
        "service.InstallmentPlanInput": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "installments": {
                    "type": "integer"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "purchased_on": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "integer"
                }
            }
        },
        "service.PaymentMethod": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "bank": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "credit_limit": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last4": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "opening_balance": {
                    "type": "integer"
                },
                "opening_balance_date": {
                    "type": "string"
                },
                "payment_due_day": {
                    "type": "integer"
                },
                "statement_day": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.PaymentMethodInput": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "bank": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "credit_limit": {
                    "type": "integer"
                },
                "last4": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "opening_balance": {
                    "type": "integer"
                },
                "opening_balance_date": {
                    "type": "string"
                },
                "payment_due_day": {
                    "type": "integer"
                },
                "statement_day": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.ProfileInput": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "service.RegisterInput": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "service.SeriesPoint": {
            "type": "object",
            "properties": {
                "committed": {
                    "type": "integer"
                },
                "expenses": {
                    "type": "integer"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "service.Session": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/service.User"
                }
            }
        },
        "service.Statement": {
            "type": "object",
            "properties": {
                "amount_due": {
                    "type": "integer"
                },
                "available_credit": {
                    "type": "integer"
                },
                "billed_balance": {
                    "type": "integer"
                },
                "charges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.StatementCharge"
                    }
                },
                "closes_on": {
                    "type": "string"
                },
                "credit_limit": {
                    "type": "integer"
                },
                "current_balance": {
                    "type": "integer"
                },
                "cycle": {
                    "type": "string"
                },
                "due_on": {
                    "type": "string"
                },
                "installments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.StatementInstallment"
                    }
                },
                "opens_on": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.CardPayment"
                    }
                },
                "utilization": {
                    "type": "number"
                }
            }
        },
        "service.StatementCharge": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "service.StatementInstallment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "no": {
                    "type": "integer"
                },
                "of": {
                    "type": "integer"
                },
                "plan_id": {
                    "type": "integer"
                }
            }
        },
        "service.Summary": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "budgets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.BudgetStatus"
                    }
                },
                "currency": {
                    "type": "string"
                },
                "days_remaining": {
                    "type": "integer"
                },
                "fixed_committed": {
                    "type": "integer"
                },
                "fixed_paid": {
                    "type": "integer"
                },
                "income": {
                    "type": "integer"
                },
                "installments": {
                    "type": "integer"
                },
                "month": {
                    "type": "string"
                },
                "safe_to_spend_per_day": {
                    "type": "integer"
                },
                "spent": {
                    "type": "integer"
                }
            }
        },
        "service.UpcomingItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "entry_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "overdue": {
                    "type": "boolean"
                },
                "payment_method_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locale": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Finance API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
