// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cards.sql

package store

import (
	"context"
	"time"
)

const cancelInstallmentPlan = `-- name: CancelInstallmentPlan :one
UPDATE installment_plans SET cancelled_on = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, payment_method_id, category_id, description, total_amount, installments, purchased_on, cancelled_on, created_at, updated_at
`

type CancelInstallmentPlanParams struct {
	CancelledOn *time.Time
	ID          int64
	UserID      int64
}

func (q *Queries) CancelInstallmentPlan(ctx context.Context, arg CancelInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, cancelInstallmentPlan, arg.CancelledOn, arg.ID, arg.UserID)
	var i InstallmentPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentMethodID,
		&i.CategoryID,
		&i.Description,
		&i.TotalAmount,
		&i.Installments,
		&i.PurchasedOn,
		&i.CancelledOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cardCharges = `-- name: CardCharges :many
SELECT e.spent_on AS charged_on, e.amount, e.description, 'expense'::text AS source
FROM expenses e
WHERE e.user_id = $1 AND e.payment_method_id = $2
UNION ALL
SELECT COALESCE(m.settled_on, m.due_date) AS charged_on, m.amount, m.name AS description, 'fixed'::text AS source
FROM monthly_entries m
WHERE m.user_id = $1 AND m.payment_method_id = $2 AND m.kind = 'fixed' AND m.status = 'paid'
ORDER BY charged_on
`

type CardChargesParams struct {
	UserID          int64
	PaymentMethodID *int64
}

type CardChargesRow struct {
	ChargedOn   time.Time
	Amount      int64
	Description string
	Source      string
}

func (q *Queries) CardCharges(ctx context.Context, arg CardChargesParams) ([]CardChargesRow, error) {
	rows, err := q.db.Query(ctx, cardCharges, arg.UserID, arg.PaymentMethodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardChargesRow
	for rows.Next() {
		var i CardChargesRow
		if err := rows.Scan(
			&i.ChargedOn,
			&i.Amount,
			&i.Description,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cardPaymentsFor = `-- name: CardPaymentsFor :many
SELECT id, user_id, payment_method_id, amount, paid_on, note, created_at, updated_at FROM card_payments WHERE user_id = $1 AND payment_method_id = $2 ORDER BY paid_on, id
`

type CardPaymentsForParams struct {
	UserID          int64
	PaymentMethodID int64
}

func (q *Queries) CardPaymentsFor(ctx context.Context, arg CardPaymentsForParams) ([]CardPayment, error) {
	rows, err := q.db.Query(ctx, cardPaymentsFor, arg.UserID, arg.PaymentMethodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardPayment
	for rows.Next() {
		var i CardPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.PaidOn,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCardPayment = `-- name: CreateCardPayment :one
INSERT INTO card_payments (user_id, payment_method_id, amount, paid_on, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, payment_method_id, amount, paid_on, note, created_at, updated_at
`

type CreateCardPaymentParams struct {
	UserID          int64
	PaymentMethodID int64
	Amount          int64
	PaidOn          time.Time
	Note            string
}

func (q *Queries) CreateCardPayment(ctx context.Context, arg CreateCardPaymentParams) (CardPayment, error) {
	row := q.db.QueryRow(ctx, createCardPayment,
		arg.UserID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.PaidOn,
		arg.Note,
	)
	var i CardPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.PaidOn,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstallmentPlan = `-- name: CreateInstallmentPlan :one
INSERT INTO installment_plans (user_id, payment_method_id, category_id, description, total_amount, installments, purchased_on)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, payment_method_id, category_id, description, total_amount, installments, purchased_on, cancelled_on, created_at, updated_at
`

type CreateInstallmentPlanParams struct {
	UserID          int64
	PaymentMethodID int64
	CategoryID      int64
	Description     string
	TotalAmount     int64
	Installments    int32
	PurchasedOn     time.Time
}

func (q *Queries) CreateInstallmentPlan(ctx context.Context, arg CreateInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, createInstallmentPlan,
		arg.UserID,
		arg.PaymentMethodID,
		arg.CategoryID,
		arg.Description,
		arg.TotalAmount,
		arg.Installments,
		arg.PurchasedOn,
	)
	var i InstallmentPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentMethodID,
		&i.CategoryID,
		&i.Description,
		&i.TotalAmount,
		&i.Installments,
		&i.PurchasedOn,
		&i.CancelledOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCardPayment = `-- name: DeleteCardPayment :execrows
DELETE FROM card_payments WHERE id = $1 AND user_id = $2
`

type DeleteCardPaymentParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCardPayment(ctx context.Context, arg DeleteCardPaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCardPayment, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstallmentPlan = `-- name: GetInstallmentPlan :one
SELECT id, user_id, payment_method_id, category_id, description, total_amount, installments, purchased_on, cancelled_on, created_at, updated_at FROM installment_plans WHERE id = $1 AND user_id = $2
`

type GetInstallmentPlanParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetInstallmentPlan(ctx context.Context, arg GetInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, getInstallmentPlan, arg.ID, arg.UserID)
	var i InstallmentPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentMethodID,
		&i.CategoryID,
		&i.Description,
		&i.TotalAmount,
		&i.Installments,
		&i.PurchasedOn,
		&i.CancelledOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardPayments = `-- name: ListCardPayments :many
SELECT id, user_id, payment_method_id, amount, paid_on, note, created_at, updated_at FROM card_payments
WHERE user_id = $1
  AND ($2::bigint IS NULL OR payment_method_id = $2::bigint)
  AND ($3::date IS NULL OR paid_on >= $3::date)
  AND ($4::date IS NULL OR paid_on <= $4::date)
ORDER BY paid_on DESC, id DESC
`

type ListCardPaymentsParams struct {
	UserID          int64
	PaymentMethodID *int64
	FromDate        *time.Time
	ToDate          *time.Time
}

func (q *Queries) ListCardPayments(ctx context.Context, arg ListCardPaymentsParams) ([]CardPayment, error) {
	rows, err := q.db.Query(ctx, listCardPayments,
		arg.UserID,
		arg.PaymentMethodID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardPayment
	for rows.Next() {
		var i CardPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.PaidOn,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentPlans = `-- name: ListInstallmentPlans :many
SELECT id, user_id, payment_method_id, category_id, description, total_amount, installments, purchased_on, cancelled_on, created_at, updated_at FROM installment_plans
WHERE user_id = $1
  AND ($2::bigint IS NULL OR payment_method_id = $2::bigint)
  AND (NOT $3::bool OR cancelled_on IS NULL)
ORDER BY purchased_on DESC, id DESC
`

type ListInstallmentPlansParams struct {
	UserID          int64
	PaymentMethodID *int64
	ActiveOnly      bool
}

func (q *Queries) ListInstallmentPlans(ctx context.Context, arg ListInstallmentPlansParams) ([]InstallmentPlan, error) {
	rows, err := q.db.Query(ctx, listInstallmentPlans, arg.UserID, arg.PaymentMethodID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPlan
	for rows.Next() {
		var i InstallmentPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentMethodID,
			&i.CategoryID,
			&i.Description,
			&i.TotalAmount,
			&i.Installments,
			&i.PurchasedOn,
			&i.CancelledOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const plansForCard = `-- name: PlansForCard :many
SELECT id, user_id, payment_method_id, category_id, description, total_amount, installments, purchased_on, cancelled_on, created_at, updated_at FROM installment_plans WHERE user_id = $1 AND payment_method_id = $2 ORDER BY purchased_on, id
`

type PlansForCardParams struct {
	UserID          int64
	PaymentMethodID int64
}

func (q *Queries) PlansForCard(ctx context.Context, arg PlansForCardParams) ([]InstallmentPlan, error) {
	rows, err := q.db.Query(ctx, plansForCard, arg.UserID, arg.PaymentMethodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPlan
	for rows.Next() {
		var i InstallmentPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentMethodID,
			&i.CategoryID,
			&i.Description,
			&i.TotalAmount,
			&i.Installments,
			&i.PurchasedOn,
			&i.CancelledOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallmentPlan = `-- name: UpdateInstallmentPlan :one
UPDATE installment_plans SET payment_method_id = $1, category_id = $2, description = $3,
    total_amount = $4, installments = $5, purchased_on = $6, updated_at = now()
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, payment_method_id, category_id, description, total_amount, installments, purchased_on, cancelled_on, created_at, updated_at
`

type UpdateInstallmentPlanParams struct {
	PaymentMethodID int64
	CategoryID      int64
	Description     string
	TotalAmount     int64
	Installments    int32
	PurchasedOn     time.Time
	ID              int64
	UserID          int64
}

func (q *Queries) UpdateInstallmentPlan(ctx context.Context, arg UpdateInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, updateInstallmentPlan,
		arg.PaymentMethodID,
		arg.CategoryID,
		arg.Description,
		arg.TotalAmount,
		arg.Installments,
		arg.PurchasedOn,
		arg.ID,
		arg.UserID,
	)
	var i InstallmentPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentMethodID,
		&i.CategoryID,
		&i.Description,
		&i.TotalAmount,
		&i.Installments,
		&i.PurchasedOn,
		&i.CancelledOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
