// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package store

import (
	"context"
)

const categoryUsage = `-- name: CategoryUsage :one
SELECT ((SELECT count(*) FROM expenses e WHERE e.category_id = $1)
      + (SELECT count(*) FROM fixed_payments f WHERE f.category_id = $1)
      + (SELECT count(*) FROM income_sources i WHERE i.category_id = $1)
      + (SELECT count(*) FROM monthly_entries m WHERE m.category_id = $1)
      + (SELECT count(*) FROM installment_plans p WHERE p.category_id = $1))::bigint AS uses
`

func (q *Queries) CategoryUsage(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, categoryUsage, id)
	var uses int64
	err := row.Scan(&uses)
	return uses, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, kind, color, icon)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, kind, color, icon, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID int64
	Name   string
	Kind   string
	Color  string
	Icon   string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, name, kind, color, icon, created_at, updated_at FROM categories WHERE id = $1 AND user_id = $2
`

type GetCategoryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, kind, color, icon, created_at, updated_at FROM categories
WHERE user_id = $1 AND ($2::text IS NULL OR kind = $2)
ORDER BY kind, name
`

type ListCategoriesParams struct {
	UserID int64
	Kind   *string
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignEntriesCategory = `-- name: ReassignEntriesCategory :exec
UPDATE monthly_entries SET category_id = $1, updated_at = now() WHERE category_id = $2
`

type ReassignEntriesCategoryParams struct {
	ToID   *int64
	FromID *int64
}

func (q *Queries) ReassignEntriesCategory(ctx context.Context, arg ReassignEntriesCategoryParams) error {
	_, err := q.db.Exec(ctx, reassignEntriesCategory, arg.ToID, arg.FromID)
	return err
}

const reassignExpensesCategory = `-- name: ReassignExpensesCategory :exec
UPDATE expenses SET category_id = $1, updated_at = now() WHERE category_id = $2
`

type ReassignExpensesCategoryParams struct {
	ToID   int64
	FromID int64
}

func (q *Queries) ReassignExpensesCategory(ctx context.Context, arg ReassignExpensesCategoryParams) error {
	_, err := q.db.Exec(ctx, reassignExpensesCategory, arg.ToID, arg.FromID)
	return err
}

const reassignFixedCategory = `-- name: ReassignFixedCategory :exec
UPDATE fixed_payments SET category_id = $1, updated_at = now() WHERE category_id = $2
`

type ReassignFixedCategoryParams struct {
	ToID   int64
	FromID int64
}

func (q *Queries) ReassignFixedCategory(ctx context.Context, arg ReassignFixedCategoryParams) error {
	_, err := q.db.Exec(ctx, reassignFixedCategory, arg.ToID, arg.FromID)
	return err
}

const reassignIncomeCategory = `-- name: ReassignIncomeCategory :exec
UPDATE income_sources SET category_id = $1, updated_at = now() WHERE category_id = $2
`

type ReassignIncomeCategoryParams struct {
	ToID   *int64
	FromID *int64
}

func (q *Queries) ReassignIncomeCategory(ctx context.Context, arg ReassignIncomeCategoryParams) error {
	_, err := q.db.Exec(ctx, reassignIncomeCategory, arg.ToID, arg.FromID)
	return err
}

const reassignPlansCategory = `-- name: ReassignPlansCategory :exec
UPDATE installment_plans SET category_id = $1, updated_at = now() WHERE category_id = $2
`

type ReassignPlansCategoryParams struct {
	ToID   int64
	FromID int64
}

func (q *Queries) ReassignPlansCategory(ctx context.Context, arg ReassignPlansCategoryParams) error {
	_, err := q.db.Exec(ctx, reassignPlansCategory, arg.ToID, arg.FromID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $1, color = $2, icon = $3, updated_at = now()
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, name, kind, color, icon, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name   string
	Color  string
	Icon   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
