// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package store

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, kind, color, icon)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, kind, color, icon, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID int64
	Name   string
	Kind   string
	Color  string
	Icon   string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
