// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package store

import (
	"context"
	"time"
)

const breakdownByCategory = `-- name: BreakdownByCategory :many
SELECT c.id, c.name, c.color, SUM(x.amount)::bigint AS amount
FROM (
    SELECT e.category_id, e.amount FROM expenses e
    WHERE e.user_id = $1 AND e.spent_on BETWEEN $2::date AND $3::date
    UNION ALL
    SELECT m.category_id, m.amount FROM monthly_entries m
    WHERE m.user_id = $1 AND m.kind IN ('fixed', 'installment') AND m.status <> 'skipped'
      AND m.due_date BETWEEN $2::date AND $3::date
) x
JOIN categories c ON c.id = x.category_id
GROUP BY c.id, c.name, c.color
ORDER BY amount DESC, c.name
`

type BreakdownByCategoryParams struct {
	UserID   int64
	FromDate time.Time
	ToDate   time.Time
}

type BreakdownByCategoryRow struct {
	ID     int64
	Name   string
	Color  string
	Amount int64
}

func (q *Queries) BreakdownByCategory(ctx context.Context, arg BreakdownByCategoryParams) ([]BreakdownByCategoryRow, error) {
	rows, err := q.db.Query(ctx, breakdownByCategory, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BreakdownByCategoryRow
	for rows.Next() {
		var i BreakdownByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const breakdownByPaymentMethod = `-- name: BreakdownByPaymentMethod :many
SELECT pm.id, pm.nickname, pm.color, SUM(x.amount)::bigint AS amount
FROM (
    SELECT e.payment_method_id, e.amount FROM expenses e
    WHERE e.user_id = $1 AND e.spent_on BETWEEN $2::date AND $3::date
    UNION ALL
    SELECT m.payment_method_id, m.amount FROM monthly_entries m
    WHERE m.user_id = $1 AND m.kind IN ('fixed', 'installment') AND m.status <> 'skipped'
      AND m.due_date BETWEEN $2::date AND $3::date
) x
LEFT JOIN payment_methods pm ON pm.id = x.payment_method_id
GROUP BY pm.id, pm.nickname, pm.color
ORDER BY amount DESC
`

type BreakdownByPaymentMethodParams struct {
	UserID   int64
	FromDate time.Time
	ToDate   time.Time
}

type BreakdownByPaymentMethodRow struct {
	ID       *int64
	Nickname *string
	Color    *string
	Amount   int64
}

func (q *Queries) BreakdownByPaymentMethod(ctx context.Context, arg BreakdownByPaymentMethodParams) ([]BreakdownByPaymentMethodRow, error) {
	rows, err := q.db.Query(ctx, breakdownByPaymentMethod, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BreakdownByPaymentMethodRow
	for rows.Next() {
		var i BreakdownByPaymentMethodRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Color,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const budgetStatus = `-- name: BudgetStatus :many
SELECT b.category_id, c.name, c.color, b.monthly_limit,
    (COALESCE((SELECT SUM(e.amount) FROM expenses e
               WHERE e.user_id = b.user_id AND e.category_id = b.category_id
                 AND e.spent_on >= $1::date AND e.spent_on < ($1::date + INTERVAL '1 month')), 0)
   + COALESCE((SELECT SUM(m.amount) FROM monthly_entries m
               WHERE m.user_id = b.user_id AND m.category_id = b.category_id AND m.month = $1::date
                 AND m.kind IN ('fixed', 'installment') AND m.status <> 'skipped'), 0))::bigint AS spent
FROM category_budgets b
JOIN categories c ON c.id = b.category_id
WHERE b.user_id = $2
ORDER BY c.name
`

type BudgetStatusParams struct {
	Month  time.Time
	UserID int64
}

type BudgetStatusRow struct {
	CategoryID   int64
	Name         string
	Color        string
	MonthlyLimit int64
	Spent        int64
}

func (q *Queries) BudgetStatus(ctx context.Context, arg BudgetStatusParams) ([]BudgetStatusRow, error) {
	rows, err := q.db.Query(ctx, budgetStatus, arg.Month, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetStatusRow
	for rows.Next() {
		var i BudgetStatusRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Color,
			&i.MonthlyLimit,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCategoryBudget = `-- name: DeleteCategoryBudget :execrows
DELETE FROM category_budgets WHERE user_id = $1 AND category_id = $2
`

type DeleteCategoryBudgetParams struct {
	UserID     int64
	CategoryID int64
}

func (q *Queries) DeleteCategoryBudget(ctx context.Context, arg DeleteCategoryBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategoryBudget, arg.UserID, arg.CategoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportEntries = `-- name: ExportEntries :many
SELECT m.month, m.kind, m.name, c.name AS category, pm.nickname AS payment_method, m.due_date, m.status, m.amount
FROM monthly_entries m
LEFT JOIN categories c ON c.id = m.category_id
LEFT JOIN payment_methods pm ON pm.id = m.payment_method_id
WHERE m.user_id = $1 AND m.due_date BETWEEN $2::date AND $3::date
ORDER BY m.due_date, m.id
`

type ExportEntriesParams struct {
	UserID   int64
	FromDate time.Time
	ToDate   time.Time
}

type ExportEntriesRow struct {
	Month         time.Time
	Kind          string
	Name          string
	Category      *string
	PaymentMethod *string
	DueDate       time.Time
	Status        string
	Amount        int64
}

func (q *Queries) ExportEntries(ctx context.Context, arg ExportEntriesParams) ([]ExportEntriesRow, error) {
	rows, err := q.db.Query(ctx, exportEntries, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportEntriesRow
	for rows.Next() {
		var i ExportEntriesRow
		if err := rows.Scan(
			&i.Month,
			&i.Kind,
			&i.Name,
			&i.Category,
			&i.PaymentMethod,
			&i.DueDate,
			&i.Status,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportExpenses = `-- name: ExportExpenses :many
SELECT e.spent_on, c.name AS category, pm.nickname AS payment_method, e.description, e.amount
FROM expenses e
JOIN categories c ON c.id = e.category_id
LEFT JOIN payment_methods pm ON pm.id = e.payment_method_id
WHERE e.user_id = $1 AND e.spent_on BETWEEN $2::date AND $3::date
ORDER BY e.spent_on, e.id
`

type ExportExpensesParams struct {
	UserID   int64
	FromDate time.Time
	ToDate   time.Time
}

type ExportExpensesRow struct {
	SpentOn       time.Time
	Category      string
	PaymentMethod *string
	Description   string
	Amount        int64
}

func (q *Queries) ExportExpenses(ctx context.Context, arg ExportExpensesParams) ([]ExportExpensesRow, error) {
	rows, err := q.db.Query(ctx, exportExpenses, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportExpensesRow
	for rows.Next() {
		var i ExportExpensesRow
		if err := rows.Scan(
			&i.SpentOn,
			&i.Category,
			&i.PaymentMethod,
			&i.Description,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryBudgets = `-- name: ListCategoryBudgets :many
SELECT id, user_id, category_id, monthly_limit, created_at, updated_at FROM category_budgets WHERE user_id = $1 ORDER BY category_id
`

func (q *Queries) ListCategoryBudgets(ctx context.Context, userID int64) ([]CategoryBudget, error) {
	rows, err := q.db.Query(ctx, listCategoryBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryBudget
	for rows.Next() {
		var i CategoryBudget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.MonthlyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthTotals = `-- name: MonthTotals :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE kind = 'income' AND status <> 'skipped'), 0)::bigint AS income,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'fixed' AND status <> 'skipped'), 0)::bigint AS fixed_committed,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'fixed' AND status = 'paid'), 0)::bigint AS fixed_paid,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'installment' AND status <> 'skipped'), 0)::bigint AS installments
FROM monthly_entries
WHERE user_id = $1 AND month = $2
`

type MonthTotalsParams struct {
	UserID int64
	Month  time.Time
}

type MonthTotalsRow struct {
	Income         int64
	FixedCommitted int64
	FixedPaid      int64
	Installments   int64
}

func (q *Queries) MonthTotals(ctx context.Context, arg MonthTotalsParams) (MonthTotalsRow, error) {
	row := q.db.QueryRow(ctx, monthTotals, arg.UserID, arg.Month)
	var i MonthTotalsRow
	err := row.Scan(
		&i.Income,
		&i.FixedCommitted,
		&i.FixedPaid,
		&i.Installments,
	)
	return i, err
}

const spendingSeries = `-- name: SpendingSeries :many
WITH buckets AS (
    SELECT gs::date AS start
    FROM generate_series(date_trunc($1::text, $2::date::timestamp),
                         date_trunc($1::text, $3::date::timestamp),
                         ('1 ' || $1::text)::interval) AS gs
),
ex AS (
    SELECT date_trunc($1::text, e.spent_on::timestamp)::date AS start, SUM(e.amount) AS total
    FROM expenses e
    WHERE e.user_id = $4 AND e.spent_on BETWEEN $2::date AND $3::date
    GROUP BY 1
),
fx AS (
    SELECT date_trunc($1::text, m.due_date::timestamp)::date AS start, SUM(m.amount) AS total
    FROM monthly_entries m
    WHERE m.user_id = $4 AND m.kind IN ('fixed', 'installment') AND m.status <> 'skipped'
      AND m.due_date BETWEEN $2::date AND $3::date
    GROUP BY 1
)
SELECT b.start::date AS start, COALESCE(ex.total, 0)::bigint AS expenses, COALESCE(fx.total, 0)::bigint AS committed
FROM buckets b
LEFT JOIN ex ON ex.start = b.start
LEFT JOIN fx ON fx.start = b.start
ORDER BY b.start
`

type SpendingSeriesParams struct {
	Period   string
	FromDate time.Time
	ToDate   time.Time
	UserID   int64
}

type SpendingSeriesRow struct {
	Start     time.Time
	Expenses  int64
	Committed int64
}

func (q *Queries) SpendingSeries(ctx context.Context, arg SpendingSeriesParams) ([]SpendingSeriesRow, error) {
	rows, err := q.db.Query(ctx, spendingSeries,
		arg.Period,
		arg.FromDate,
		arg.ToDate,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpendingSeriesRow
	for rows.Next() {
		var i SpendingSeriesRow
		if err := rows.Scan(&i.Start, &i.Expenses, &i.Committed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spentBetween = `-- name: SpentBetween :one
SELECT COALESCE(SUM(amount), 0)::bigint AS spent
FROM expenses
WHERE user_id = $1 AND spent_on BETWEEN $2::date AND $3::date
`

type SpentBetweenParams struct {
	UserID   int64
	FromDate time.Time
	ToDate   time.Time
}

func (q *Queries) SpentBetween(ctx context.Context, arg SpentBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, spentBetween, arg.UserID, arg.FromDate, arg.ToDate)
	var spent int64
	err := row.Scan(&spent)
	return spent, err
}

const upcomingFixedEntries = `-- name: UpcomingFixedEntries :many
SELECT id, user_id, month, kind, income_source_id, fixed_payment_id, installment_plan_id, installment_no, name, category_id, payment_method_id, amount, due_date, status, settled_on, edited, created_at, updated_at, occurrence FROM monthly_entries
WHERE user_id = $1 AND kind = 'fixed' AND status = 'pending'
  AND due_date BETWEEN $2::date AND $3::date
ORDER BY due_date, id
`

type UpcomingFixedEntriesParams struct {
	UserID   int64
	FromDate time.Time
	ToDate   time.Time
}

func (q *Queries) UpcomingFixedEntries(ctx context.Context, arg UpcomingFixedEntriesParams) ([]MonthlyEntry, error) {
	rows, err := q.db.Query(ctx, upcomingFixedEntries, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyEntry
	for rows.Next() {
		var i MonthlyEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.Kind,
			&i.IncomeSourceID,
			&i.FixedPaymentID,
			&i.InstallmentPlanID,
			&i.InstallmentNo,
			&i.Name,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.SettledOn,
			&i.Edited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Occurrence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategoryBudget = `-- name: UpsertCategoryBudget :one
INSERT INTO category_budgets (user_id, category_id, monthly_limit)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, category_id) DO UPDATE SET monthly_limit = EXCLUDED.monthly_limit, updated_at = now()
RETURNING id, user_id, category_id, monthly_limit, created_at, updated_at
`

type UpsertCategoryBudgetParams struct {
	UserID       int64
	CategoryID   int64
	MonthlyLimit int64
}

func (q *Queries) UpsertCategoryBudget(ctx context.Context, arg UpsertCategoryBudgetParams) (CategoryBudget, error) {
	row := q.db.QueryRow(ctx, upsertCategoryBudget, arg.UserID, arg.CategoryID, arg.MonthlyLimit)
	var i CategoryBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.MonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
