// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package store

import (
	"context"
	"time"
)

const budgetStatus = `-- name: BudgetStatus :many
SELECT b.category_id, c.name, c.color, b.monthly_limit,
    (COALESCE((SELECT SUM(e.amount) FROM expenses e
               WHERE e.user_id = b.user_id AND e.category_id = b.category_id
                 AND e.spent_on >= $1::date AND e.spent_on < ($1::date + INTERVAL '1 month')), 0)
   + COALESCE((SELECT SUM(m.amount) FROM monthly_entries m
               WHERE m.user_id = b.user_id AND m.category_id = b.category_id AND m.month = $1::date
                 AND m.kind IN ('fixed', 'installment') AND m.status <> 'skipped'), 0))::bigint AS spent
FROM category_budgets b
JOIN categories c ON c.id = b.category_id
WHERE b.user_id = $2
ORDER BY c.name
`

type BudgetStatusParams struct {
	Month  time.Time
	UserID int64
}

type BudgetStatusRow struct {
	CategoryID   int64
	Name         string
	Color        string
	MonthlyLimit int64
	Spent        int64
}

func (q *Queries) BudgetStatus(ctx context.Context, arg BudgetStatusParams) ([]BudgetStatusRow, error) {
	rows, err := q.db.Query(ctx, budgetStatus, arg.Month, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetStatusRow
	for rows.Next() {
		var i BudgetStatusRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Color,
			&i.MonthlyLimit,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCategoryBudget = `-- name: DeleteCategoryBudget :execrows
DELETE FROM category_budgets WHERE user_id = $1 AND category_id = $2
`

type DeleteCategoryBudgetParams struct {
	UserID     int64
	CategoryID int64
}

func (q *Queries) DeleteCategoryBudget(ctx context.Context, arg DeleteCategoryBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategoryBudget, arg.UserID, arg.CategoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCategoryBudgets = `-- name: ListCategoryBudgets :many
SELECT id, user_id, category_id, monthly_limit, created_at, updated_at FROM category_budgets WHERE user_id = $1 ORDER BY category_id
`

func (q *Queries) ListCategoryBudgets(ctx context.Context, userID int64) ([]CategoryBudget, error) {
	rows, err := q.db.Query(ctx, listCategoryBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryBudget
	for rows.Next() {
		var i CategoryBudget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.MonthlyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthTotals = `-- name: MonthTotals :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE kind = 'income' AND status <> 'skipped'), 0)::bigint AS income,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'fixed' AND status <> 'skipped'), 0)::bigint AS fixed_committed,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'fixed' AND status = 'paid'), 0)::bigint AS fixed_paid,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'installment' AND status <> 'skipped'), 0)::bigint AS installments
FROM monthly_entries
WHERE user_id = $1 AND month = $2
`

type MonthTotalsParams struct {
	UserID int64
	Month  time.Time
}

type MonthTotalsRow struct {
	Income         int64
	FixedCommitted int64
	FixedPaid      int64
	Installments   int64
}

func (q *Queries) MonthTotals(ctx context.Context, arg MonthTotalsParams) (MonthTotalsRow, error) {
	row := q.db.QueryRow(ctx, monthTotals, arg.UserID, arg.Month)
	var i MonthTotalsRow
	err := row.Scan(
		&i.Income,
		&i.FixedCommitted,
		&i.FixedPaid,
		&i.Installments,
	)
	return i, err
}

const spentBetween = `-- name: SpentBetween :one
SELECT COALESCE(SUM(amount), 0)::bigint AS spent
FROM expenses
WHERE user_id = $1 AND spent_on BETWEEN $2::date AND $3::date
`

type SpentBetweenParams struct {
	UserID   int64
	FromDate time.Time
	ToDate   time.Time
}

func (q *Queries) SpentBetween(ctx context.Context, arg SpentBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, spentBetween, arg.UserID, arg.FromDate, arg.ToDate)
	var spent int64
	err := row.Scan(&spent)
	return spent, err
}

const upsertCategoryBudget = `-- name: UpsertCategoryBudget :one
INSERT INTO category_budgets (user_id, category_id, monthly_limit)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, category_id) DO UPDATE SET monthly_limit = EXCLUDED.monthly_limit, updated_at = now()
RETURNING id, user_id, category_id, monthly_limit, created_at, updated_at
`

type UpsertCategoryBudgetParams struct {
	UserID       int64
	CategoryID   int64
	MonthlyLimit int64
}

func (q *Queries) UpsertCategoryBudget(ctx context.Context, arg UpsertCategoryBudgetParams) (CategoryBudget, error) {
	row := q.db.QueryRow(ctx, upsertCategoryBudget, arg.UserID, arg.CategoryID, arg.MonthlyLimit)
	var i CategoryBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.MonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
