// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entries.sql

package store

import (
	"context"
	"time"
)

const deleteInstallmentEntries = `-- name: DeleteInstallmentEntries :exec
DELETE FROM monthly_entries
WHERE user_id = $1 AND installment_plan_id = $2::bigint AND installment_no >= $3::int
`

type DeleteInstallmentEntriesParams struct {
	UserID int64
	PlanID int64
	FromNo int32
}

func (q *Queries) DeleteInstallmentEntries(ctx context.Context, arg DeleteInstallmentEntriesParams) error {
	_, err := q.db.Exec(ctx, deleteInstallmentEntries, arg.UserID, arg.PlanID, arg.FromNo)
	return err
}

const ensureFixedEntries = `-- name: EnsureFixedEntries :exec
INSERT INTO monthly_entries (user_id, month, kind, fixed_payment_id, name, category_id, payment_method_id, amount, due_date)
SELECT f.user_id, $1::date, 'fixed', f.id, f.name, f.category_id, f.payment_method_id, f.amount,
       $1::date + (LEAST(f.day_of_month, EXTRACT(DAY FROM ($1::date + INTERVAL '1 month' - INTERVAL '1 day'))::int) - 1)
FROM fixed_payments f
WHERE f.user_id = $2 AND (f.active OR f.end_month IS NOT NULL)
  AND f.start_month <= $1::date AND (f.end_month IS NULL OR f.end_month >= $1::date)
ON CONFLICT DO NOTHING
`

type EnsureFixedEntriesParams struct {
	Month  time.Time
	UserID int64
}

func (q *Queries) EnsureFixedEntries(ctx context.Context, arg EnsureFixedEntriesParams) error {
	_, err := q.db.Exec(ctx, ensureFixedEntries, arg.Month, arg.UserID)
	return err
}

const ensureIncomeEntries = `-- name: EnsureIncomeEntries :exec
INSERT INTO monthly_entries (user_id, month, kind, income_source_id, name, category_id, amount, due_date)
SELECT s.user_id, $1::date, 'income', s.id, s.name, s.category_id, s.amount,
       $1::date + (LEAST(s.day_of_month, EXTRACT(DAY FROM ($1::date + INTERVAL '1 month' - INTERVAL '1 day'))::int) - 1)
FROM income_sources s
WHERE s.user_id = $2 AND (s.active OR s.end_month IS NOT NULL)
  AND s.start_month <= $1::date AND (s.end_month IS NULL OR s.end_month >= $1::date)
ON CONFLICT DO NOTHING
`

type EnsureIncomeEntriesParams struct {
	Month  time.Time
	UserID int64
}

// Inactive templates keep generating up to their (clamped) end_month; an inactive
// template without one never started (see DeactivateIncomeSource).
func (q *Queries) EnsureIncomeEntries(ctx context.Context, arg EnsureIncomeEntriesParams) error {
	_, err := q.db.Exec(ctx, ensureIncomeEntries, arg.Month, arg.UserID)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, month, kind, income_source_id, fixed_payment_id, installment_plan_id, installment_no, name, category_id, payment_method_id, amount, due_date, status, settled_on, edited, created_at, updated_at FROM monthly_entries WHERE id = $1 AND user_id = $2
`

type GetEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (MonthlyEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.ID, arg.UserID)
	var i MonthlyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Kind,
		&i.IncomeSourceID,
		&i.FixedPaymentID,
		&i.InstallmentPlanID,
		&i.InstallmentNo,
		&i.Name,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.SettledOn,
		&i.Edited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInstallmentEntry = `-- name: InsertInstallmentEntry :exec
INSERT INTO monthly_entries (user_id, month, kind, installment_plan_id, installment_no, name, category_id,
    payment_method_id, amount, due_date)
VALUES ($1, $2::date, 'installment', $3::bigint, $4::int, $5,
    $6::bigint, $7::bigint, $8, $9::date)
ON CONFLICT DO NOTHING
`

type InsertInstallmentEntryParams struct {
	UserID            int64
	Month             time.Time
	InstallmentPlanID int64
	InstallmentNo     int32
	Name              string
	CategoryID        int64
	PaymentMethodID   int64
	Amount            int64
	DueDate           time.Time
}

func (q *Queries) InsertInstallmentEntry(ctx context.Context, arg InsertInstallmentEntryParams) error {
	_, err := q.db.Exec(ctx, insertInstallmentEntry,
		arg.UserID,
		arg.Month,
		arg.InstallmentPlanID,
		arg.InstallmentNo,
		arg.Name,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.DueDate,
	)
	return err
}

const listMonthEntries = `-- name: ListMonthEntries :many
SELECT id, user_id, month, kind, income_source_id, fixed_payment_id, installment_plan_id, installment_no, name, category_id, payment_method_id, amount, due_date, status, settled_on, edited, created_at, updated_at FROM monthly_entries
WHERE user_id = $1 AND month = $2
ORDER BY CASE kind WHEN 'income' THEN 0 WHEN 'fixed' THEN 1 ELSE 2 END, due_date, id
`

type ListMonthEntriesParams struct {
	UserID int64
	Month  time.Time
}

func (q *Queries) ListMonthEntries(ctx context.Context, arg ListMonthEntriesParams) ([]MonthlyEntry, error) {
	rows, err := q.db.Query(ctx, listMonthEntries, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyEntry
	for rows.Next() {
		var i MonthlyEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.Kind,
			&i.IncomeSourceID,
			&i.FixedPaymentID,
			&i.InstallmentPlanID,
			&i.InstallmentNo,
			&i.Name,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.SettledOn,
			&i.Edited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansForEnsure = `-- name: ListPlansForEnsure :many
SELECT p.id, p.description, p.total_amount, p.installments, p.purchased_on, p.cancelled_on,
       p.category_id, p.payment_method_id, pm.statement_day, pm.payment_due_day
FROM installment_plans p
JOIN payment_methods pm ON pm.id = p.payment_method_id
WHERE p.user_id = $1
`

type ListPlansForEnsureRow struct {
	ID              int64
	Description     string
	TotalAmount     int64
	Installments    int32
	PurchasedOn     time.Time
	CancelledOn     *time.Time
	CategoryID      int64
	PaymentMethodID int64
	StatementDay    *int32
	PaymentDueDay   *int32
}

func (q *Queries) ListPlansForEnsure(ctx context.Context, userID int64) ([]ListPlansForEnsureRow, error) {
	rows, err := q.db.Query(ctx, listPlansForEnsure, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansForEnsureRow
	for rows.Next() {
		var i ListPlansForEnsureRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.TotalAmount,
			&i.Installments,
			&i.PurchasedOn,
			&i.CancelledOn,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.StatementDay,
			&i.PaymentDueDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const propagateFixedPayment = `-- name: PropagateFixedPayment :exec
UPDATE monthly_entries m SET name = f.name, amount = f.amount, category_id = f.category_id,
    payment_method_id = f.payment_method_id,
    due_date = m.month + (LEAST(f.day_of_month, EXTRACT(DAY FROM (m.month + INTERVAL '1 month' - INTERVAL '1 day'))::int) - 1),
    updated_at = now()
FROM fixed_payments f
WHERE f.id = $1 AND m.fixed_payment_id = f.id
  AND m.month >= $2::date AND m.status = 'pending' AND NOT m.edited
`

type PropagateFixedPaymentParams struct {
	SourceID  int64
	FromMonth time.Time
}

func (q *Queries) PropagateFixedPayment(ctx context.Context, arg PropagateFixedPaymentParams) error {
	_, err := q.db.Exec(ctx, propagateFixedPayment, arg.SourceID, arg.FromMonth)
	return err
}

const propagateIncomeSource = `-- name: PropagateIncomeSource :exec
UPDATE monthly_entries m SET name = s.name, amount = s.amount, category_id = s.category_id,
    due_date = m.month + (LEAST(s.day_of_month, EXTRACT(DAY FROM (m.month + INTERVAL '1 month' - INTERVAL '1 day'))::int) - 1),
    updated_at = now()
FROM income_sources s
WHERE s.id = $1 AND m.income_source_id = s.id
  AND m.month >= $2::date AND m.status = 'pending' AND NOT m.edited
`

type PropagateIncomeSourceParams struct {
	SourceID  int64
	FromMonth time.Time
}

func (q *Queries) PropagateIncomeSource(ctx context.Context, arg PropagateIncomeSourceParams) error {
	_, err := q.db.Exec(ctx, propagateIncomeSource, arg.SourceID, arg.FromMonth)
	return err
}

const pruneFixedEntries = `-- name: PruneFixedEntries :exec
DELETE FROM monthly_entries m
USING fixed_payments f
WHERE f.id = $1 AND m.fixed_payment_id = f.id
  AND m.status = 'pending' AND NOT m.edited AND m.month >= $2::date
  AND ((NOT f.active AND m.month > $2::date)
       OR (f.end_month IS NOT NULL AND m.month > f.end_month)
       OR m.month < f.start_month)
`

type PruneFixedEntriesParams struct {
	SourceID  int64
	FromMonth time.Time
}

func (q *Queries) PruneFixedEntries(ctx context.Context, arg PruneFixedEntriesParams) error {
	_, err := q.db.Exec(ctx, pruneFixedEntries, arg.SourceID, arg.FromMonth)
	return err
}

const pruneIncomeEntries = `-- name: PruneIncomeEntries :exec
DELETE FROM monthly_entries m
USING income_sources s
WHERE s.id = $1 AND m.income_source_id = s.id
  AND m.status = 'pending' AND NOT m.edited AND m.month >= $2::date
  AND ((NOT s.active AND m.month > $2::date)
       OR (s.end_month IS NOT NULL AND m.month > s.end_month)
       OR m.month < s.start_month)
`

type PruneIncomeEntriesParams struct {
	SourceID  int64
	FromMonth time.Time
}

func (q *Queries) PruneIncomeEntries(ctx context.Context, arg PruneIncomeEntriesParams) error {
	_, err := q.db.Exec(ctx, pruneIncomeEntries, arg.SourceID, arg.FromMonth)
	return err
}

const relabelInstallmentEntries = `-- name: RelabelInstallmentEntries :exec
UPDATE monthly_entries
SET name = $1::text || ' ' || installment_no::text || '/' || $2::int::text,
    category_id = $3::bigint, updated_at = now()
WHERE user_id = $4 AND installment_plan_id = $5::bigint
`

type RelabelInstallmentEntriesParams struct {
	Description  string
	Installments int32
	CategoryID   int64
	UserID       int64
	PlanID       int64
}

func (q *Queries) RelabelInstallmentEntries(ctx context.Context, arg RelabelInstallmentEntriesParams) error {
	_, err := q.db.Exec(ctx, relabelInstallmentEntries,
		arg.Description,
		arg.Installments,
		arg.CategoryID,
		arg.UserID,
		arg.PlanID,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE monthly_entries SET amount = $1, status = $2, settled_on = $3,
    payment_method_id = $4, edited = $5, updated_at = now()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, month, kind, income_source_id, fixed_payment_id, installment_plan_id, installment_no, name, category_id, payment_method_id, amount, due_date, status, settled_on, edited, created_at, updated_at
`

type UpdateEntryParams struct {
	Amount          int64
	Status          string
	SettledOn       *time.Time
	PaymentMethodID *int64
	Edited          bool
	ID              int64
	UserID          int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (MonthlyEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.Amount,
		arg.Status,
		arg.SettledOn,
		arg.PaymentMethodID,
		arg.Edited,
		arg.ID,
		arg.UserID,
	)
	var i MonthlyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Kind,
		&i.IncomeSourceID,
		&i.FixedPaymentID,
		&i.InstallmentPlanID,
		&i.InstallmentNo,
		&i.Name,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.SettledOn,
		&i.Edited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
