// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entries.sql

package store

import (
	"context"
	"time"
)

const deleteCardPendingInstallments = `-- name: DeleteCardPendingInstallments :exec
DELETE FROM monthly_entries m
USING installment_plans p
WHERE m.user_id = $1 AND m.kind = 'installment' AND m.status = 'pending'
  AND m.installment_plan_id = p.id AND p.user_id = $1
  AND p.payment_method_id = $2::bigint
`

type DeleteCardPendingInstallmentsParams struct {
	UserID          int64
	PaymentMethodID int64
}

// After a card's cut-off/due day changes, pending installment rows may sit in the
// wrong month; drop them so ensureInstallments regenerates them with the new mapping.
func (q *Queries) DeleteCardPendingInstallments(ctx context.Context, arg DeleteCardPendingInstallmentsParams) error {
	_, err := q.db.Exec(ctx, deleteCardPendingInstallments, arg.UserID, arg.PaymentMethodID)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM monthly_entries WHERE id = $1 AND user_id = $2
`

type DeleteEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.Exec(ctx, deleteEntry, arg.ID, arg.UserID)
	return err
}

const deleteInstallmentEntries = `-- name: DeleteInstallmentEntries :exec
DELETE FROM monthly_entries
WHERE user_id = $1 AND installment_plan_id = $2::bigint AND installment_no >= $3::int
`

type DeleteInstallmentEntriesParams struct {
	UserID int64
	PlanID int64
	FromNo int32
}

func (q *Queries) DeleteInstallmentEntries(ctx context.Context, arg DeleteInstallmentEntriesParams) error {
	_, err := q.db.Exec(ctx, deleteInstallmentEntries, arg.UserID, arg.PlanID, arg.FromNo)
	return err
}

const ensureFixedEntries = `-- name: EnsureFixedEntries :exec
INSERT INTO monthly_entries (user_id, month, kind, fixed_payment_id, name, category_id, payment_method_id, amount, due_date)
SELECT f.user_id, $1::date, 'fixed', f.id, f.name, f.category_id, f.payment_method_id, f.amount,
       $1::date + (LEAST(f.day_of_month, EXTRACT(DAY FROM ($1::date + INTERVAL '1 month' - INTERVAL '1 day'))::int) - 1)
FROM fixed_payments f
WHERE f.user_id = $2 AND (f.active OR f.end_month IS NOT NULL)
  AND f.start_month <= $1::date AND (f.end_month IS NULL OR f.end_month >= $1::date)
ON CONFLICT DO NOTHING
`

type EnsureFixedEntriesParams struct {
	Month  time.Time
	UserID int64
}

func (q *Queries) EnsureFixedEntries(ctx context.Context, arg EnsureFixedEntriesParams) error {
	_, err := q.db.Exec(ctx, ensureFixedEntries, arg.Month, arg.UserID)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, month, kind, income_source_id, fixed_payment_id, installment_plan_id, installment_no, name, category_id, payment_method_id, amount, due_date, status, settled_on, edited, created_at, updated_at, occurrence FROM monthly_entries WHERE id = $1 AND user_id = $2
`

type GetEntryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (MonthlyEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.ID, arg.UserID)
	var i MonthlyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Kind,
		&i.IncomeSourceID,
		&i.FixedPaymentID,
		&i.InstallmentPlanID,
		&i.InstallmentNo,
		&i.Name,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.SettledOn,
		&i.Edited,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Occurrence,
	)
	return i, err
}

const insertIncomeEntry = `-- name: InsertIncomeEntry :exec
INSERT INTO monthly_entries (user_id, month, kind, income_source_id, occurrence, name, category_id, amount, due_date)
VALUES ($1, $2::date, 'income', $3::bigint, $4::int, $5,
    $6, $7, $8::date)
ON CONFLICT DO NOTHING
`

type InsertIncomeEntryParams struct {
	UserID     int64
	Month      time.Time
	SourceID   int64
	Occurrence int32
	Name       string
	CategoryID *int64
	Amount     int64
	DueDate    time.Time
}

func (q *Queries) InsertIncomeEntry(ctx context.Context, arg InsertIncomeEntryParams) error {
	_, err := q.db.Exec(ctx, insertIncomeEntry,
		arg.UserID,
		arg.Month,
		arg.SourceID,
		arg.Occurrence,
		arg.Name,
		arg.CategoryID,
		arg.Amount,
		arg.DueDate,
	)
	return err
}

const insertInstallmentEntry = `-- name: InsertInstallmentEntry :exec
INSERT INTO monthly_entries (user_id, month, kind, installment_plan_id, installment_no, name, category_id,
    payment_method_id, amount, due_date)
VALUES ($1, $2::date, 'installment', $3::bigint, $4::int, $5,
    $6::bigint, $7::bigint, $8, $9::date)
ON CONFLICT DO NOTHING
`

type InsertInstallmentEntryParams struct {
	UserID            int64
	Month             time.Time
	InstallmentPlanID int64
	InstallmentNo     int32
	Name              string
	CategoryID        int64
	PaymentMethodID   int64
	Amount            int64
	DueDate           time.Time
}

func (q *Queries) InsertInstallmentEntry(ctx context.Context, arg InsertInstallmentEntryParams) error {
	_, err := q.db.Exec(ctx, insertInstallmentEntry,
		arg.UserID,
		arg.Month,
		arg.InstallmentPlanID,
		arg.InstallmentNo,
		arg.Name,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.DueDate,
	)
	return err
}

const listIncomeOccurrences = `-- name: ListIncomeOccurrences :many
SELECT income_source_id, occurrence FROM monthly_entries
WHERE user_id = $1 AND month = $2::date AND kind = 'income'
`

type ListIncomeOccurrencesParams struct {
	UserID int64
	Month  time.Time
}

type ListIncomeOccurrencesRow struct {
	IncomeSourceID *int64
	Occurrence     int32
}

func (q *Queries) ListIncomeOccurrences(ctx context.Context, arg ListIncomeOccurrencesParams) ([]ListIncomeOccurrencesRow, error) {
	rows, err := q.db.Query(ctx, listIncomeOccurrences, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomeOccurrencesRow
	for rows.Next() {
		var i ListIncomeOccurrencesRow
		if err := rows.Scan(&i.IncomeSourceID, &i.Occurrence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeSourcesForMonth = `-- name: ListIncomeSourcesForMonth :many
SELECT id, user_id, category_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at, frequency, second_day, anchor_date FROM income_sources s
WHERE s.user_id = $1 AND (s.active OR s.end_month IS NOT NULL)
  AND s.start_month <= $2::date AND (s.end_month IS NULL OR s.end_month >= $2::date)
ORDER BY s.id
`

type ListIncomeSourcesForMonthParams struct {
	UserID int64
	Month  time.Time
}

// Inactive templates keep generating up to their (clamped) end_month; an inactive
// template without one never started (see DeactivateIncomeSource).
func (q *Queries) ListIncomeSourcesForMonth(ctx context.Context, arg ListIncomeSourcesForMonthParams) ([]IncomeSource, error) {
	rows, err := q.db.Query(ctx, listIncomeSourcesForMonth, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeSource
	for rows.Next() {
		var i IncomeSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.DayOfMonth,
			&i.StartMonth,
			&i.EndMonth,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Frequency,
			&i.SecondDay,
			&i.AnchorDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthEntries = `-- name: ListMonthEntries :many
SELECT id, user_id, month, kind, income_source_id, fixed_payment_id, installment_plan_id, installment_no, name, category_id, payment_method_id, amount, due_date, status, settled_on, edited, created_at, updated_at, occurrence FROM monthly_entries
WHERE user_id = $1 AND month = $2
ORDER BY CASE kind WHEN 'income' THEN 0 WHEN 'fixed' THEN 1 ELSE 2 END, due_date, id
`

type ListMonthEntriesParams struct {
	UserID int64
	Month  time.Time
}

func (q *Queries) ListMonthEntries(ctx context.Context, arg ListMonthEntriesParams) ([]MonthlyEntry, error) {
	rows, err := q.db.Query(ctx, listMonthEntries, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyEntry
	for rows.Next() {
		var i MonthlyEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.Kind,
			&i.IncomeSourceID,
			&i.FixedPaymentID,
			&i.InstallmentPlanID,
			&i.InstallmentNo,
			&i.Name,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.SettledOn,
			&i.Edited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Occurrence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingIncomeEntries = `-- name: ListPendingIncomeEntries :many
SELECT id, month, occurrence FROM monthly_entries
WHERE user_id = $1 AND income_source_id = $2::bigint
  AND month >= $3::date AND status = 'pending' AND NOT edited
ORDER BY month, occurrence
`

type ListPendingIncomeEntriesParams struct {
	UserID    int64
	SourceID  int64
	FromMonth time.Time
}

type ListPendingIncomeEntriesRow struct {
	ID         int64
	Month      time.Time
	Occurrence int32
}

// The rows a template edit may still rewrite: pending, never edited by hand.
func (q *Queries) ListPendingIncomeEntries(ctx context.Context, arg ListPendingIncomeEntriesParams) ([]ListPendingIncomeEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingIncomeEntries, arg.UserID, arg.SourceID, arg.FromMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingIncomeEntriesRow
	for rows.Next() {
		var i ListPendingIncomeEntriesRow
		if err := rows.Scan(&i.ID, &i.Month, &i.Occurrence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansForEnsure = `-- name: ListPlansForEnsure :many
SELECT p.id, p.description, p.total_amount, p.installments, p.purchased_on, p.cancelled_on,
       p.category_id, p.payment_method_id, pm.statement_day, pm.payment_due_day
FROM installment_plans p
JOIN payment_methods pm ON pm.id = p.payment_method_id
WHERE p.user_id = $1
`

type ListPlansForEnsureRow struct {
	ID              int64
	Description     string
	TotalAmount     int64
	Installments    int32
	PurchasedOn     time.Time
	CancelledOn     *time.Time
	CategoryID      int64
	PaymentMethodID int64
	StatementDay    *int32
	PaymentDueDay   *int32
}

func (q *Queries) ListPlansForEnsure(ctx context.Context, userID int64) ([]ListPlansForEnsureRow, error) {
	rows, err := q.db.Query(ctx, listPlansForEnsure, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansForEnsureRow
	for rows.Next() {
		var i ListPlansForEnsureRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.TotalAmount,
			&i.Installments,
			&i.PurchasedOn,
			&i.CancelledOn,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.StatementDay,
			&i.PaymentDueDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const propagateFixedPayment = `-- name: PropagateFixedPayment :exec
UPDATE monthly_entries m SET name = f.name, amount = f.amount, category_id = f.category_id,
    payment_method_id = f.payment_method_id,
    due_date = m.month + (LEAST(f.day_of_month, EXTRACT(DAY FROM (m.month + INTERVAL '1 month' - INTERVAL '1 day'))::int) - 1),
    updated_at = now()
FROM fixed_payments f
WHERE f.id = $1 AND f.user_id = $2 AND m.user_id = $2 AND m.fixed_payment_id = f.id
  AND m.month >= $3::date AND m.status = 'pending' AND NOT m.edited
`

type PropagateFixedPaymentParams struct {
	SourceID  int64
	UserID    int64
	FromMonth time.Time
}

func (q *Queries) PropagateFixedPayment(ctx context.Context, arg PropagateFixedPaymentParams) error {
	_, err := q.db.Exec(ctx, propagateFixedPayment, arg.SourceID, arg.UserID, arg.FromMonth)
	return err
}

const pruneFixedEntries = `-- name: PruneFixedEntries :exec
DELETE FROM monthly_entries m
USING fixed_payments f
WHERE f.id = $1 AND f.user_id = $2 AND m.user_id = $2 AND m.fixed_payment_id = f.id
  AND m.status = 'pending' AND NOT m.edited AND m.month >= $3::date
  AND ((NOT f.active AND m.month > $3::date)
       OR (f.end_month IS NOT NULL AND m.month > f.end_month)
       OR m.month < f.start_month)
`

type PruneFixedEntriesParams struct {
	SourceID  int64
	UserID    int64
	FromMonth time.Time
}

func (q *Queries) PruneFixedEntries(ctx context.Context, arg PruneFixedEntriesParams) error {
	_, err := q.db.Exec(ctx, pruneFixedEntries, arg.SourceID, arg.UserID, arg.FromMonth)
	return err
}

const pruneIncomeEntries = `-- name: PruneIncomeEntries :exec
DELETE FROM monthly_entries m
USING income_sources s
WHERE s.id = $1 AND s.user_id = $2 AND m.user_id = $2 AND m.income_source_id = s.id
  AND m.status = 'pending' AND NOT m.edited AND m.month >= $3::date
  AND ((NOT s.active AND m.month > $3::date)
       OR (s.end_month IS NOT NULL AND m.month > s.end_month)
       OR m.month < s.start_month)
`

type PruneIncomeEntriesParams struct {
	SourceID  int64
	UserID    int64
	FromMonth time.Time
}

func (q *Queries) PruneIncomeEntries(ctx context.Context, arg PruneIncomeEntriesParams) error {
	_, err := q.db.Exec(ctx, pruneIncomeEntries, arg.SourceID, arg.UserID, arg.FromMonth)
	return err
}

const relabelInstallmentEntries = `-- name: RelabelInstallmentEntries :exec
UPDATE monthly_entries
SET name = $1::text || ' ' || installment_no::text || '/' || $2::int::text,
    category_id = $3::bigint, updated_at = now()
WHERE user_id = $4 AND installment_plan_id = $5::bigint
`

type RelabelInstallmentEntriesParams struct {
	Description  string
	Installments int32
	CategoryID   int64
	UserID       int64
	PlanID       int64
}

func (q *Queries) RelabelInstallmentEntries(ctx context.Context, arg RelabelInstallmentEntriesParams) error {
	_, err := q.db.Exec(ctx, relabelInstallmentEntries,
		arg.Description,
		arg.Installments,
		arg.CategoryID,
		arg.UserID,
		arg.PlanID,
	)
	return err
}

const syncIncomeEntry = `-- name: SyncIncomeEntry :exec
UPDATE monthly_entries SET name = $1, amount = $2, category_id = $3,
    due_date = $4::date, updated_at = now()
WHERE id = $5 AND user_id = $6
`

type SyncIncomeEntryParams struct {
	Name       string
	Amount     int64
	CategoryID *int64
	DueDate    time.Time
	ID         int64
	UserID     int64
}

func (q *Queries) SyncIncomeEntry(ctx context.Context, arg SyncIncomeEntryParams) error {
	_, err := q.db.Exec(ctx, syncIncomeEntry,
		arg.Name,
		arg.Amount,
		arg.CategoryID,
		arg.DueDate,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE monthly_entries SET amount = $1, status = $2, settled_on = $3,
    payment_method_id = $4, edited = $5, updated_at = now()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, month, kind, income_source_id, fixed_payment_id, installment_plan_id, installment_no, name, category_id, payment_method_id, amount, due_date, status, settled_on, edited, created_at, updated_at, occurrence
`

type UpdateEntryParams struct {
	Amount          int64
	Status          string
	SettledOn       *time.Time
	PaymentMethodID *int64
	Edited          bool
	ID              int64
	UserID          int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (MonthlyEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.Amount,
		arg.Status,
		arg.SettledOn,
		arg.PaymentMethodID,
		arg.Edited,
		arg.ID,
		arg.UserID,
	)
	var i MonthlyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Kind,
		&i.IncomeSourceID,
		&i.FixedPaymentID,
		&i.InstallmentPlanID,
		&i.InstallmentNo,
		&i.Name,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.SettledOn,
		&i.Edited,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Occurrence,
	)
	return i, err
}
