// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: expenses.sql

package store

import (
	"context"
	"time"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, category_id, payment_method_id, amount, description, spent_on)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, category_id, payment_method_id, amount, description, spent_on, created_at, updated_at
`

type CreateExpenseParams struct {
	UserID          int64
	CategoryID      int64
	PaymentMethodID *int64
	Amount          int64
	Description     string
	SpentOn         time.Time
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Description,
		arg.SpentOn,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Description,
		&i.SpentOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :execrows
DELETE FROM expenses WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, user_id, category_id, payment_method_id, amount, description, spent_on, created_at, updated_at FROM expenses
WHERE user_id = $1
  AND ($2::date IS NULL OR spent_on >= $2::date)
  AND ($3::date IS NULL OR spent_on <= $3::date)
  AND ($4::bigint IS NULL OR category_id = $4::bigint)
  AND ($5::bigint IS NULL OR payment_method_id = $5::bigint)
  AND ($6::text IS NULL OR description ILIKE '%' || $6::text || '%')
  AND ($7::date IS NULL OR (spent_on, id) < ($7::date, $8::bigint))
ORDER BY spent_on DESC, id DESC
LIMIT $9
`

type ListExpensesParams struct {
	UserID          int64
	FromDate        *time.Time
	ToDate          *time.Time
	CategoryID      *int64
	PaymentMethodID *int64
	Q               *string
	CursorDate      *time.Time
	CursorID        *int64
	Lim             int32
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Q,
		arg.CursorDate,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Description,
			&i.SpentOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET category_id = $1, payment_method_id = $2, amount = $3,
    description = $4, spent_on = $5, updated_at = now()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, category_id, payment_method_id, amount, description, spent_on, created_at, updated_at
`

type UpdateExpenseParams struct {
	CategoryID      int64
	PaymentMethodID *int64
	Amount          int64
	Description     string
	SpentOn         time.Time
	ID              int64
	UserID          int64
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Description,
		arg.SpentOn,
		arg.ID,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Description,
		&i.SpentOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
