// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"
)

type CardPayment struct {
	ID              int64
	UserID          int64
	PaymentMethodID int64
	Amount          int64
	PaidOn          time.Time
	Note            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Category struct {
	ID        int64
	UserID    int64
	Name      string
	Kind      string
	Color     string
	Icon      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CategoryBudget struct {
	ID           int64
	UserID       int64
	CategoryID   int64
	MonthlyLimit int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Expense struct {
	ID              int64
	UserID          int64
	CategoryID      int64
	PaymentMethodID *int64
	Amount          int64
	Description     string
	SpentOn         time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type FixedPayment struct {
	ID              int64
	UserID          int64
	CategoryID      int64
	PaymentMethodID *int64
	Name            string
	Amount          int64
	DayOfMonth      int32
	StartMonth      time.Time
	EndMonth        *time.Time
	Active          bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type IncomeSource struct {
	ID         int64
	UserID     int64
	CategoryID *int64
	Name       string
	Amount     int64
	DayOfMonth int32
	StartMonth time.Time
	EndMonth   *time.Time
	Active     bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type InstallmentPlan struct {
	ID              int64
	UserID          int64
	PaymentMethodID int64
	CategoryID      int64
	Description     string
	TotalAmount     int64
	Installments    int32
	PurchasedOn     time.Time
	CancelledOn     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MonthlyEntry struct {
	ID                int64
	UserID            int64
	Month             time.Time
	Kind              string
	IncomeSourceID    *int64
	FixedPaymentID    *int64
	InstallmentPlanID *int64
	InstallmentNo     *int32
	Name              string
	CategoryID        *int64
	PaymentMethodID   *int64
	Amount            int64
	DueDate           time.Time
	Status            string
	SettledOn         *time.Time
	Edited            bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type PaymentMethod struct {
	ID                 int64
	UserID             int64
	Nickname           string
	Type               string
	Bank               *string
	Network            *string
	Last4              *string
	Color              string
	Active             bool
	CreditLimit        *int64
	StatementDay       *int32
	PaymentDueDay      *int32
	OpeningBalance     int64
	OpeningBalanceDate *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	FamilyID  string
	TokenHash string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         string
	Currency     string
	Locale       string
	Timezone     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
