// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_methods.sql

package store

import (
	"context"
	"time"
)

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (user_id, nickname, type, bank, network, last4, color, active,
    credit_limit, statement_day, payment_due_day, opening_balance, opening_balance_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13)
RETURNING id, user_id, nickname, type, bank, network, last4, color, active, credit_limit, statement_day, payment_due_day, opening_balance, opening_balance_date, created_at, updated_at
`

type CreatePaymentMethodParams struct {
	UserID             int64
	Nickname           string
	Type               string
	Bank               *string
	Network            *string
	Last4              *string
	Color              string
	Active             bool
	CreditLimit        *int64
	StatementDay       *int32
	PaymentDueDay      *int32
	OpeningBalance     int64
	OpeningBalanceDate *time.Time
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.UserID,
		arg.Nickname,
		arg.Type,
		arg.Bank,
		arg.Network,
		arg.Last4,
		arg.Color,
		arg.Active,
		arg.CreditLimit,
		arg.StatementDay,
		arg.PaymentDueDay,
		arg.OpeningBalance,
		arg.OpeningBalanceDate,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.Type,
		&i.Bank,
		&i.Network,
		&i.Last4,
		&i.Color,
		&i.Active,
		&i.CreditLimit,
		&i.StatementDay,
		&i.PaymentDueDay,
		&i.OpeningBalance,
		&i.OpeningBalanceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePaymentMethod = `-- name: DeletePaymentMethod :execrows
DELETE FROM payment_methods WHERE id = $1 AND user_id = $2
`

type DeletePaymentMethodParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePaymentMethod(ctx context.Context, arg DeletePaymentMethodParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePaymentMethod, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT id, user_id, nickname, type, bank, network, last4, color, active, credit_limit, statement_day, payment_due_day, opening_balance, opening_balance_date, created_at, updated_at FROM payment_methods WHERE id = $1 AND user_id = $2
`

type GetPaymentMethodParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetPaymentMethod(ctx context.Context, arg GetPaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, arg.ID, arg.UserID)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.Type,
		&i.Bank,
		&i.Network,
		&i.Last4,
		&i.Color,
		&i.Active,
		&i.CreditLimit,
		&i.StatementDay,
		&i.PaymentDueDay,
		&i.OpeningBalance,
		&i.OpeningBalanceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditCards = `-- name: ListCreditCards :many
SELECT id, user_id, nickname, type, bank, network, last4, color, active, credit_limit, statement_day, payment_due_day, opening_balance, opening_balance_date, created_at, updated_at FROM payment_methods WHERE user_id = $1 AND type = 'credit' ORDER BY nickname, id
`

// Includes inactive cards: callers keep those that still carry a balance.
func (q *Queries) ListCreditCards(ctx context.Context, userID int64) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listCreditCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nickname,
			&i.Type,
			&i.Bank,
			&i.Network,
			&i.Last4,
			&i.Color,
			&i.Active,
			&i.CreditLimit,
			&i.StatementDay,
			&i.PaymentDueDay,
			&i.OpeningBalance,
			&i.OpeningBalanceDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT id, user_id, nickname, type, bank, network, last4, color, active, credit_limit, statement_day, payment_due_day, opening_balance, opening_balance_date, created_at, updated_at FROM payment_methods WHERE user_id = $1 ORDER BY active DESC, nickname, id
`

func (q *Queries) ListPaymentMethods(ctx context.Context, userID int64) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nickname,
			&i.Type,
			&i.Bank,
			&i.Network,
			&i.Last4,
			&i.Color,
			&i.Active,
			&i.CreditLimit,
			&i.StatementDay,
			&i.PaymentDueDay,
			&i.OpeningBalance,
			&i.OpeningBalanceDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentMethodUsage = `-- name: PaymentMethodUsage :one
SELECT ((SELECT count(*) FROM expenses e WHERE e.payment_method_id = $1 AND e.user_id = $2)
      + (SELECT count(*) FROM fixed_payments f WHERE f.payment_method_id = $1 AND f.user_id = $2)
      + (SELECT count(*) FROM monthly_entries m WHERE m.payment_method_id = $1 AND m.user_id = $2)
      + (SELECT count(*) FROM installment_plans p WHERE p.payment_method_id = $1 AND p.user_id = $2)
      + (SELECT count(*) FROM card_payments c WHERE c.payment_method_id = $1 AND c.user_id = $2))::bigint AS uses
`

type PaymentMethodUsageParams struct {
	ID     *int64
	UserID int64
}

func (q *Queries) PaymentMethodUsage(ctx context.Context, arg PaymentMethodUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, paymentMethodUsage, arg.ID, arg.UserID)
	var uses int64
	err := row.Scan(&uses)
	return uses, err
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE payment_methods SET nickname = $1, bank = $2, network = $3,
    last4 = $4, color = $5, active = $6, credit_limit = $7,
    statement_day = $8, payment_due_day = $9,
    opening_balance = $10, opening_balance_date = $11, updated_at = now()
WHERE id = $12 AND user_id = $13
RETURNING id, user_id, nickname, type, bank, network, last4, color, active, credit_limit, statement_day, payment_due_day, opening_balance, opening_balance_date, created_at, updated_at
`

type UpdatePaymentMethodParams struct {
	Nickname           string
	Bank               *string
	Network            *string
	Last4              *string
	Color              string
	Active             bool
	CreditLimit        *int64
	StatementDay       *int32
	PaymentDueDay      *int32
	OpeningBalance     int64
	OpeningBalanceDate *time.Time
	ID                 int64
	UserID             int64
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.Nickname,
		arg.Bank,
		arg.Network,
		arg.Last4,
		arg.Color,
		arg.Active,
		arg.CreditLimit,
		arg.StatementDay,
		arg.PaymentDueDay,
		arg.OpeningBalance,
		arg.OpeningBalanceDate,
		arg.ID,
		arg.UserID,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.Type,
		&i.Bank,
		&i.Network,
		&i.Last4,
		&i.Color,
		&i.Active,
		&i.CreditLimit,
		&i.StatementDay,
		&i.PaymentDueDay,
		&i.OpeningBalance,
		&i.OpeningBalanceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
