// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recurring.sql

package store

import (
	"context"
	"time"
)

const createFixedPayment = `-- name: CreateFixedPayment :one
INSERT INTO fixed_payments (user_id, category_id, payment_method_id, name, amount, day_of_month, start_month, end_month, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, category_id, payment_method_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at
`

type CreateFixedPaymentParams struct {
	UserID          int64
	CategoryID      int64
	PaymentMethodID *int64
	Name            string
	Amount          int64
	DayOfMonth      int32
	StartMonth      time.Time
	EndMonth        *time.Time
	Active          bool
}

func (q *Queries) CreateFixedPayment(ctx context.Context, arg CreateFixedPaymentParams) (FixedPayment, error) {
	row := q.db.QueryRow(ctx, createFixedPayment,
		arg.UserID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Name,
		arg.Amount,
		arg.DayOfMonth,
		arg.StartMonth,
		arg.EndMonth,
		arg.Active,
	)
	var i FixedPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Name,
		&i.Amount,
		&i.DayOfMonth,
		&i.StartMonth,
		&i.EndMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncomeSource = `-- name: CreateIncomeSource :one
INSERT INTO income_sources (user_id, category_id, name, amount, frequency, day_of_month, second_day, anchor_date, start_month, end_month, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11)
RETURNING id, user_id, category_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at, frequency, second_day, anchor_date
`

type CreateIncomeSourceParams struct {
	UserID     int64
	CategoryID *int64
	Name       string
	Amount     int64
	Frequency  string
	DayOfMonth int32
	SecondDay  *int32
	AnchorDate *time.Time
	StartMonth time.Time
	EndMonth   *time.Time
	Active     bool
}

func (q *Queries) CreateIncomeSource(ctx context.Context, arg CreateIncomeSourceParams) (IncomeSource, error) {
	row := q.db.QueryRow(ctx, createIncomeSource,
		arg.UserID,
		arg.CategoryID,
		arg.Name,
		arg.Amount,
		arg.Frequency,
		arg.DayOfMonth,
		arg.SecondDay,
		arg.AnchorDate,
		arg.StartMonth,
		arg.EndMonth,
		arg.Active,
	)
	var i IncomeSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.DayOfMonth,
		&i.StartMonth,
		&i.EndMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Frequency,
		&i.SecondDay,
		&i.AnchorDate,
	)
	return i, err
}

const deactivateFixedPayment = `-- name: DeactivateFixedPayment :one
UPDATE fixed_payments SET active = false,
    end_month = CASE WHEN start_month <= $1::date THEN LEAST(end_month, $1::date) END,
    updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, category_id, payment_method_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at
`

type DeactivateFixedPaymentParams struct {
	CurrentMonth time.Time
	ID           int64
	UserID       int64
}

// Ends the template at the current month (NULL when it has not started yet: nothing to keep).
func (q *Queries) DeactivateFixedPayment(ctx context.Context, arg DeactivateFixedPaymentParams) (FixedPayment, error) {
	row := q.db.QueryRow(ctx, deactivateFixedPayment, arg.CurrentMonth, arg.ID, arg.UserID)
	var i FixedPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Name,
		&i.Amount,
		&i.DayOfMonth,
		&i.StartMonth,
		&i.EndMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateIncomeSource = `-- name: DeactivateIncomeSource :one
UPDATE income_sources SET active = false,
    end_month = CASE WHEN start_month <= $1::date THEN LEAST(end_month, $1::date) END,
    updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, category_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at, frequency, second_day, anchor_date
`

type DeactivateIncomeSourceParams struct {
	CurrentMonth time.Time
	ID           int64
	UserID       int64
}

// Ends the template at the current month (NULL when it has not started yet: nothing to keep).
func (q *Queries) DeactivateIncomeSource(ctx context.Context, arg DeactivateIncomeSourceParams) (IncomeSource, error) {
	row := q.db.QueryRow(ctx, deactivateIncomeSource, arg.CurrentMonth, arg.ID, arg.UserID)
	var i IncomeSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.DayOfMonth,
		&i.StartMonth,
		&i.EndMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Frequency,
		&i.SecondDay,
		&i.AnchorDate,
	)
	return i, err
}

const listFixedPayments = `-- name: ListFixedPayments :many
SELECT id, user_id, category_id, payment_method_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at FROM fixed_payments WHERE user_id = $1 ORDER BY active DESC, name, id
`

func (q *Queries) ListFixedPayments(ctx context.Context, userID int64) ([]FixedPayment, error) {
	rows, err := q.db.Query(ctx, listFixedPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FixedPayment
	for rows.Next() {
		var i FixedPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Name,
			&i.Amount,
			&i.DayOfMonth,
			&i.StartMonth,
			&i.EndMonth,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeSources = `-- name: ListIncomeSources :many
SELECT id, user_id, category_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at, frequency, second_day, anchor_date FROM income_sources WHERE user_id = $1 ORDER BY active DESC, name, id
`

func (q *Queries) ListIncomeSources(ctx context.Context, userID int64) ([]IncomeSource, error) {
	rows, err := q.db.Query(ctx, listIncomeSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeSource
	for rows.Next() {
		var i IncomeSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.DayOfMonth,
			&i.StartMonth,
			&i.EndMonth,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Frequency,
			&i.SecondDay,
			&i.AnchorDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFixedPayment = `-- name: UpdateFixedPayment :one
UPDATE fixed_payments SET category_id = $1, payment_method_id = $2, name = $3,
    amount = $4, day_of_month = $5, start_month = $6, end_month = $7,
    active = $8, updated_at = now()
WHERE id = $9 AND user_id = $10
RETURNING id, user_id, category_id, payment_method_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at
`

type UpdateFixedPaymentParams struct {
	CategoryID      int64
	PaymentMethodID *int64
	Name            string
	Amount          int64
	DayOfMonth      int32
	StartMonth      time.Time
	EndMonth        *time.Time
	Active          bool
	ID              int64
	UserID          int64
}

func (q *Queries) UpdateFixedPayment(ctx context.Context, arg UpdateFixedPaymentParams) (FixedPayment, error) {
	row := q.db.QueryRow(ctx, updateFixedPayment,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Name,
		arg.Amount,
		arg.DayOfMonth,
		arg.StartMonth,
		arg.EndMonth,
		arg.Active,
		arg.ID,
		arg.UserID,
	)
	var i FixedPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Name,
		&i.Amount,
		&i.DayOfMonth,
		&i.StartMonth,
		&i.EndMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncomeSource = `-- name: UpdateIncomeSource :one
UPDATE income_sources SET category_id = $1, name = $2, amount = $3,
    frequency = $4, day_of_month = $5, second_day = $6,
    anchor_date = $7, start_month = $8, end_month = $9,
    active = $10, updated_at = now()
WHERE id = $11 AND user_id = $12
RETURNING id, user_id, category_id, name, amount, day_of_month, start_month, end_month, active, created_at, updated_at, frequency, second_day, anchor_date
`

type UpdateIncomeSourceParams struct {
	CategoryID *int64
	Name       string
	Amount     int64
	Frequency  string
	DayOfMonth int32
	SecondDay  *int32
	AnchorDate *time.Time
	StartMonth time.Time
	EndMonth   *time.Time
	Active     bool
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateIncomeSource(ctx context.Context, arg UpdateIncomeSourceParams) (IncomeSource, error) {
	row := q.db.QueryRow(ctx, updateIncomeSource,
		arg.CategoryID,
		arg.Name,
		arg.Amount,
		arg.Frequency,
		arg.DayOfMonth,
		arg.SecondDay,
		arg.AnchorDate,
		arg.StartMonth,
		arg.EndMonth,
		arg.Active,
		arg.ID,
		arg.UserID,
	)
	var i IncomeSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.DayOfMonth,
		&i.StartMonth,
		&i.EndMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Frequency,
		&i.SecondDay,
		&i.AnchorDate,
	)
	return i, err
}
