// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: savings.sql

package store

import (
	"context"
	"time"
)

const archiveGoalsOfAccount = `-- name: ArchiveGoalsOfAccount :exec
UPDATE savings_goals SET archived = true, updated_at = now()
WHERE user_id = $1 AND account_id = $2 AND NOT archived
`

type ArchiveGoalsOfAccountParams struct {
	UserID    int64
	AccountID int64
}

func (q *Queries) ArchiveGoalsOfAccount(ctx context.Context, arg ArchiveGoalsOfAccountParams) error {
	_, err := q.db.Exec(ctx, archiveGoalsOfAccount, arg.UserID, arg.AccountID)
	return err
}

const createAccountMovement = `-- name: CreateAccountMovement :one
INSERT INTO account_movements (user_id, account_id, kind, to_account_id, goal_id, amount, occurred_on, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, account_id, kind, to_account_id, goal_id, amount, occurred_on, note, created_at, updated_at
`

type CreateAccountMovementParams struct {
	UserID      int64
	AccountID   int64
	Kind        string
	ToAccountID *int64
	GoalID      *int64
	Amount      int64
	OccurredOn  time.Time
	Note        string
}

func (q *Queries) CreateAccountMovement(ctx context.Context, arg CreateAccountMovementParams) (AccountMovement, error) {
	row := q.db.QueryRow(ctx, createAccountMovement,
		arg.UserID,
		arg.AccountID,
		arg.Kind,
		arg.ToAccountID,
		arg.GoalID,
		arg.Amount,
		arg.OccurredOn,
		arg.Note,
	)
	var i AccountMovement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Kind,
		&i.ToAccountID,
		&i.GoalID,
		&i.Amount,
		&i.OccurredOn,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSavingsAccount = `-- name: CreateSavingsAccount :one
INSERT INTO savings_accounts (user_id, name, institution, kind, color, annual_rate_bp, opening_balance, opening_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, institution, kind, color, annual_rate_bp, opening_balance, opening_date, archived_on, created_at, updated_at
`

type CreateSavingsAccountParams struct {
	UserID         int64
	Name           string
	Institution    string
	Kind           string
	Color          string
	AnnualRateBp   *int32
	OpeningBalance int64
	OpeningDate    time.Time
}

func (q *Queries) CreateSavingsAccount(ctx context.Context, arg CreateSavingsAccountParams) (SavingsAccount, error) {
	row := q.db.QueryRow(ctx, createSavingsAccount,
		arg.UserID,
		arg.Name,
		arg.Institution,
		arg.Kind,
		arg.Color,
		arg.AnnualRateBp,
		arg.OpeningBalance,
		arg.OpeningDate,
	)
	var i SavingsAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Kind,
		&i.Color,
		&i.AnnualRateBp,
		&i.OpeningBalance,
		&i.OpeningDate,
		&i.ArchivedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSavingsGoal = `-- name: CreateSavingsGoal :one
INSERT INTO savings_goals (user_id, account_id, name, kind, emergency_months, target_amount, starting_amount, target_date,
    monthly_amount, color, icon, start_month)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12)
RETURNING id, user_id, account_id, name, kind, emergency_months, target_amount, target_date, monthly_amount, color, icon, start_month, achieved_on, archived, created_at, updated_at, starting_amount
`

type CreateSavingsGoalParams struct {
	UserID          int64
	AccountID       int64
	Name            string
	Kind            string
	EmergencyMonths *int32
	TargetAmount    int64
	StartingAmount  int64
	TargetDate      *time.Time
	MonthlyAmount   *int64
	Color           string
	Icon            string
	StartMonth      time.Time
}

func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.UserID,
		arg.AccountID,
		arg.Name,
		arg.Kind,
		arg.EmergencyMonths,
		arg.TargetAmount,
		arg.StartingAmount,
		arg.TargetDate,
		arg.MonthlyAmount,
		arg.Color,
		arg.Icon,
		arg.StartMonth,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.EmergencyMonths,
		&i.TargetAmount,
		&i.TargetDate,
		&i.MonthlyAmount,
		&i.Color,
		&i.Icon,
		&i.StartMonth,
		&i.AchievedOn,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartingAmount,
	)
	return i, err
}

const deleteAccountMovement = `-- name: DeleteAccountMovement :execrows
DELETE FROM account_movements WHERE id = $1 AND user_id = $2
`

type DeleteAccountMovementParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAccountMovement(ctx context.Context, arg DeleteAccountMovementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountMovement, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAccountValuation = `-- name: DeleteAccountValuation :execrows
DELETE FROM account_valuations WHERE user_id = $1 AND account_id = $2 AND valued_on = $3
`

type DeleteAccountValuationParams struct {
	UserID    int64
	AccountID int64
	ValuedOn  time.Time
}

func (q *Queries) DeleteAccountValuation(ctx context.Context, arg DeleteAccountValuationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountValuation, arg.UserID, arg.AccountID, arg.ValuedOn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSavingsAccount = `-- name: DeleteSavingsAccount :execrows
DELETE FROM savings_accounts WHERE id = $1 AND user_id = $2
`

type DeleteSavingsAccountParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSavingsAccount(ctx context.Context, arg DeleteSavingsAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavingsAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSavingsGoal = `-- name: DeleteSavingsGoal :execrows
DELETE FROM savings_goals WHERE id = $1 AND user_id = $2
`

type DeleteSavingsGoalParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavingsGoal, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountMovement = `-- name: GetAccountMovement :one
SELECT id, user_id, account_id, kind, to_account_id, goal_id, amount, occurred_on, note, created_at, updated_at FROM account_movements WHERE id = $1 AND user_id = $2
`

type GetAccountMovementParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetAccountMovement(ctx context.Context, arg GetAccountMovementParams) (AccountMovement, error) {
	row := q.db.QueryRow(ctx, getAccountMovement, arg.ID, arg.UserID)
	var i AccountMovement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Kind,
		&i.ToAccountID,
		&i.GoalID,
		&i.Amount,
		&i.OccurredOn,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavingsAccount = `-- name: GetSavingsAccount :one
SELECT id, user_id, name, institution, kind, color, annual_rate_bp, opening_balance, opening_date, archived_on, created_at, updated_at FROM savings_accounts WHERE id = $1 AND user_id = $2
`

type GetSavingsAccountParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSavingsAccount(ctx context.Context, arg GetSavingsAccountParams) (SavingsAccount, error) {
	row := q.db.QueryRow(ctx, getSavingsAccount, arg.ID, arg.UserID)
	var i SavingsAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Kind,
		&i.Color,
		&i.AnnualRateBp,
		&i.OpeningBalance,
		&i.OpeningDate,
		&i.ArchivedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavingsGoal = `-- name: GetSavingsGoal :one
SELECT id, user_id, account_id, name, kind, emergency_months, target_amount, target_date, monthly_amount, color, icon, start_month, achieved_on, archived, created_at, updated_at, starting_amount FROM savings_goals WHERE id = $1 AND user_id = $2
`

type GetSavingsGoalParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSavingsGoal(ctx context.Context, arg GetSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, getSavingsGoal, arg.ID, arg.UserID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.EmergencyMonths,
		&i.TargetAmount,
		&i.TargetDate,
		&i.MonthlyAmount,
		&i.Color,
		&i.Icon,
		&i.StartMonth,
		&i.AchievedOn,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartingAmount,
	)
	return i, err
}

const listAccountMovementsForAccount = `-- name: ListAccountMovementsForAccount :many
SELECT id, user_id, account_id, kind, to_account_id, goal_id, amount, occurred_on, note, created_at, updated_at FROM account_movements
WHERE user_id = $1 AND (account_id = $2 OR to_account_id = $2)
  AND ($3::date IS NULL OR occurred_on >= $3::date)
  AND ($4::date IS NULL OR occurred_on <= $4::date)
ORDER BY occurred_on DESC, id DESC
`

type ListAccountMovementsForAccountParams struct {
	UserID    int64
	AccountID int64
	FromDate  *time.Time
	ToDate    *time.Time
}

func (q *Queries) ListAccountMovementsForAccount(ctx context.Context, arg ListAccountMovementsForAccountParams) ([]AccountMovement, error) {
	rows, err := q.db.Query(ctx, listAccountMovementsForAccount,
		arg.UserID,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountMovement
	for rows.Next() {
		var i AccountMovement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Kind,
			&i.ToAccountID,
			&i.GoalID,
			&i.Amount,
			&i.OccurredOn,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountMovementsForUser = `-- name: ListAccountMovementsForUser :many
SELECT id, user_id, account_id, kind, to_account_id, goal_id, amount, occurred_on, note, created_at, updated_at FROM account_movements WHERE user_id = $1 ORDER BY occurred_on, id
`

func (q *Queries) ListAccountMovementsForUser(ctx context.Context, userID int64) ([]AccountMovement, error) {
	rows, err := q.db.Query(ctx, listAccountMovementsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountMovement
	for rows.Next() {
		var i AccountMovement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Kind,
			&i.ToAccountID,
			&i.GoalID,
			&i.Amount,
			&i.OccurredOn,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountValuationsForAccount = `-- name: ListAccountValuationsForAccount :many
SELECT id, user_id, account_id, value, valued_on, created_at, updated_at FROM account_valuations WHERE user_id = $1 AND account_id = $2 ORDER BY valued_on DESC
`

type ListAccountValuationsForAccountParams struct {
	UserID    int64
	AccountID int64
}

func (q *Queries) ListAccountValuationsForAccount(ctx context.Context, arg ListAccountValuationsForAccountParams) ([]AccountValuation, error) {
	rows, err := q.db.Query(ctx, listAccountValuationsForAccount, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountValuation
	for rows.Next() {
		var i AccountValuation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Value,
			&i.ValuedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountValuationsForUser = `-- name: ListAccountValuationsForUser :many
SELECT id, user_id, account_id, value, valued_on, created_at, updated_at FROM account_valuations WHERE user_id = $1 ORDER BY account_id, valued_on
`

func (q *Queries) ListAccountValuationsForUser(ctx context.Context, userID int64) ([]AccountValuation, error) {
	rows, err := q.db.Query(ctx, listAccountValuationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountValuation
	for rows.Next() {
		var i AccountValuation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Value,
			&i.ValuedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsAccounts = `-- name: ListSavingsAccounts :many
SELECT id, user_id, name, institution, kind, color, annual_rate_bp, opening_balance, opening_date, archived_on, created_at, updated_at FROM savings_accounts WHERE user_id = $1 ORDER BY archived_on NULLS FIRST, name
`

func (q *Queries) ListSavingsAccounts(ctx context.Context, userID int64) ([]SavingsAccount, error) {
	rows, err := q.db.Query(ctx, listSavingsAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavingsAccount
	for rows.Next() {
		var i SavingsAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Institution,
			&i.Kind,
			&i.Color,
			&i.AnnualRateBp,
			&i.OpeningBalance,
			&i.OpeningDate,
			&i.ArchivedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsGoals = `-- name: ListSavingsGoals :many
SELECT id, user_id, account_id, name, kind, emergency_months, target_amount, target_date, monthly_amount, color, icon, start_month, achieved_on, archived, created_at, updated_at, starting_amount FROM savings_goals WHERE user_id = $1 ORDER BY archived, target_date NULLS LAST, id
`

func (q *Queries) ListSavingsGoals(ctx context.Context, userID int64) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listSavingsGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavingsGoal
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Name,
			&i.Kind,
			&i.EmergencyMonths,
			&i.TargetAmount,
			&i.TargetDate,
			&i.MonthlyAmount,
			&i.Color,
			&i.Icon,
			&i.StartMonth,
			&i.AchievedOn,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartingAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSavingsGoalAchieved = `-- name: SetSavingsGoalAchieved :exec
UPDATE savings_goals SET achieved_on = $1, updated_at = now() WHERE id = $2 AND user_id = $3
`

type SetSavingsGoalAchievedParams struct {
	AchievedOn *time.Time
	ID         int64
	UserID     int64
}

func (q *Queries) SetSavingsGoalAchieved(ctx context.Context, arg SetSavingsGoalAchievedParams) error {
	_, err := q.db.Exec(ctx, setSavingsGoalAchieved, arg.AchievedOn, arg.ID, arg.UserID)
	return err
}

const updateAccountMovement = `-- name: UpdateAccountMovement :one
UPDATE account_movements SET account_id = $1, kind = $2, to_account_id = $3,
    goal_id = $4, amount = $5, occurred_on = $6, note = $7, updated_at = now()
WHERE id = $8 AND user_id = $9
RETURNING id, user_id, account_id, kind, to_account_id, goal_id, amount, occurred_on, note, created_at, updated_at
`

type UpdateAccountMovementParams struct {
	AccountID   int64
	Kind        string
	ToAccountID *int64
	GoalID      *int64
	Amount      int64
	OccurredOn  time.Time
	Note        string
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateAccountMovement(ctx context.Context, arg UpdateAccountMovementParams) (AccountMovement, error) {
	row := q.db.QueryRow(ctx, updateAccountMovement,
		arg.AccountID,
		arg.Kind,
		arg.ToAccountID,
		arg.GoalID,
		arg.Amount,
		arg.OccurredOn,
		arg.Note,
		arg.ID,
		arg.UserID,
	)
	var i AccountMovement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Kind,
		&i.ToAccountID,
		&i.GoalID,
		&i.Amount,
		&i.OccurredOn,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSavingsAccount = `-- name: UpdateSavingsAccount :one
UPDATE savings_accounts SET name = $1, institution = $2, kind = $3, color = $4,
    annual_rate_bp = $5, opening_balance = $6, opening_date = $7,
    archived_on = $8, updated_at = now()
WHERE id = $9 AND user_id = $10
RETURNING id, user_id, name, institution, kind, color, annual_rate_bp, opening_balance, opening_date, archived_on, created_at, updated_at
`

type UpdateSavingsAccountParams struct {
	Name           string
	Institution    string
	Kind           string
	Color          string
	AnnualRateBp   *int32
	OpeningBalance int64
	OpeningDate    time.Time
	ArchivedOn     *time.Time
	ID             int64
	UserID         int64
}

func (q *Queries) UpdateSavingsAccount(ctx context.Context, arg UpdateSavingsAccountParams) (SavingsAccount, error) {
	row := q.db.QueryRow(ctx, updateSavingsAccount,
		arg.Name,
		arg.Institution,
		arg.Kind,
		arg.Color,
		arg.AnnualRateBp,
		arg.OpeningBalance,
		arg.OpeningDate,
		arg.ArchivedOn,
		arg.ID,
		arg.UserID,
	)
	var i SavingsAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Institution,
		&i.Kind,
		&i.Color,
		&i.AnnualRateBp,
		&i.OpeningBalance,
		&i.OpeningDate,
		&i.ArchivedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSavingsGoal = `-- name: UpdateSavingsGoal :one
UPDATE savings_goals SET name = $1, kind = $2, emergency_months = $3,
    target_amount = $4, starting_amount = $5, target_date = $6, monthly_amount = $7,
    color = $8, icon = $9, archived = $10, updated_at = now()
WHERE id = $11 AND user_id = $12
RETURNING id, user_id, account_id, name, kind, emergency_months, target_amount, target_date, monthly_amount, color, icon, start_month, achieved_on, archived, created_at, updated_at, starting_amount
`

type UpdateSavingsGoalParams struct {
	Name            string
	Kind            string
	EmergencyMonths *int32
	TargetAmount    int64
	StartingAmount  int64
	TargetDate      *time.Time
	MonthlyAmount   *int64
	Color           string
	Icon            string
	Archived        bool
	ID              int64
	UserID          int64
}

func (q *Queries) UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoal,
		arg.Name,
		arg.Kind,
		arg.EmergencyMonths,
		arg.TargetAmount,
		arg.StartingAmount,
		arg.TargetDate,
		arg.MonthlyAmount,
		arg.Color,
		arg.Icon,
		arg.Archived,
		arg.ID,
		arg.UserID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.EmergencyMonths,
		&i.TargetAmount,
		&i.TargetDate,
		&i.MonthlyAmount,
		&i.Color,
		&i.Icon,
		&i.StartMonth,
		&i.AchievedOn,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartingAmount,
	)
	return i, err
}

const upsertAccountValuation = `-- name: UpsertAccountValuation :one
INSERT INTO account_valuations (user_id, account_id, value, valued_on)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, valued_on) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING id, user_id, account_id, value, valued_on, created_at, updated_at
`

type UpsertAccountValuationParams struct {
	UserID    int64
	AccountID int64
	Value     int64
	ValuedOn  time.Time
}

func (q *Queries) UpsertAccountValuation(ctx context.Context, arg UpsertAccountValuationParams) (AccountValuation, error) {
	row := q.db.QueryRow(ctx, upsertAccountValuation,
		arg.UserID,
		arg.AccountID,
		arg.Value,
		arg.ValuedOn,
	)
	var i AccountValuation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Value,
		&i.ValuedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
