// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package store

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	UserID    int64
	FamilyID  string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, currency, locale, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, name, currency, locale, timezone, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
	Currency     string
	Locale       string
	Timezone     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Currency,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, name, currency, locale, timezone, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, currency, locale, timezone, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeRefreshByHash = `-- name: RevokeRefreshByHash :exec
UPDATE refresh_tokens SET revoked_at = $1::timestamptz WHERE token_hash = $2 AND revoked_at IS NULL
`

type RevokeRefreshByHashParams struct {
	Now       time.Time
	TokenHash string
}

func (q *Queries) RevokeRefreshByHash(ctx context.Context, arg RevokeRefreshByHashParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshByHash, arg.Now, arg.TokenHash)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens SET revoked_at = $1::timestamptz WHERE family_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshFamilyParams struct {
	Now      time.Time
	FamilyID string
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, arg.Now, arg.FamilyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at = $1::timestamptz WHERE id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	Now time.Time
	ID  int64
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $1, currency = $2, locale = $3, timezone = $4, updated_at = now()
WHERE id = $5
RETURNING id, email, password_hash, name, currency, locale, timezone, created_at, updated_at
`

type UpdateUserParams struct {
	Name     string
	Currency string
	Locale   string
	Timezone string
	ID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Currency,
		arg.Locale,
		arg.Timezone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
